#! /bin/bash

for SPEC in $@; do
    echo "Reading ${SPEC}"

    if [ ! -f ${SPEC} ]; then
    echo "Cannot find ${SPEC}"
    exit 1
    fi

    IPATH=$(grep '%global goipath ' ${SPEC} | awk '{print $3}')
    DOCS=$(grep "^${IPATH}," goipaths-docs.txt)
    SUMMARY=$(echo ${DOCS} | cut -d\, -f2 | sed -e 's/\&#44;/,/g' | sed -e 's/\//\\\//g')
    DESCRIPTION=$(echo ${DOCS} | cut -d\, -f3 | sed -e 's/\&#44;/,/g' | fold -w 79 -s | sed -e 's/\//\\\//g' | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')
    if [ "${SUMMARY}" != "" ]; then
        sed -i -e "s/^Summary:        None$/Summary:        ${SUMMARY}/g" ${SPEC}
    fi
    if [ "${DESCRIPTION}" != "" ]; then
        sed -i -e "s/^# FIXME}$/${DESCRIPTION}}/g" ${SPEC}
    fi

    VERSION=$(basename $(grep ^Version ${SPEC} | awk '{print $2}') | sed -e 's/^v//g' | sed -e 's/\-/\~/g')
    if [ "${VERSION}" != "" ]; then
        sed -i -e "s/^Version:                .*/Version:                ${VERSION}/g" ${SPEC}
    fi

    UNSORTED=$(grep -v '^for cmd in cmd/\* ; do$' ${SPEC} | grep -P '^for cmd in .*; do$')
    if [ "${UNSORTED}" != "" ]; then
        UNSORTEDITEMS=$(echo "${UNSORTED}" | sed -e 's/^for cmd in //g' | sed -e 's/; do$//g')
        SORTEDITEMS=$(for ITEM in ${UNSORTEDITEMS}; do
            echo ${ITEM}
        done | sort)
        SORTED="for cmd in"
        for ITEM in ${SORTEDITEMS}; do
            SORTED+=" ${ITEM}"
        done
        SORTED+="; do"
        ESCUNSORTED=$(echo ${UNSORTED} | sed -e 's/\//\\\//g')
        ESCSORTED=$(echo ${SORTED} | sed -e 's/\//\\\//g')
        sed -i -e "s/^${ESCUNSORTED}$/${ESCSORTED}/g" ${SPEC}
    fi

    GREPFILE=$(mktemp)
    for i in $(grep -E "^(# Upstream license specification: )" ${SPEC} | cut -d: -f2- | sed -e 's/^ //g' | sed -e 's/ /_/g' | sed -e 's/_and_/ /g'); do
        echo ${i}
    done | sort -u > ${GREPFILE}

    LINE=""
    REGEXP=$(grep '^# Upstream license specification: ' ${SPEC}  | cut -d\: -f2- | sed -e 's/^ //g' | sed -e 's/ and /|/g')
    LICS=$(grep -E "^(${REGEXP})$" ${GREPFILE} )
    for LIC in ${LICS}; do
        LINE+="${LIC} and "
    done
    SORTED=$(echo ${LINE} | sed -e 's/ and$//g' | sed -e 's/^/# Upstream license specification: /g')
    sed -i -e "s/^# Upstream license specification: .*/${SORTED}/g" ${SPEC}

    for i in $(grep -E "^(License: )" ${SPEC} | cut -d: -f2- | sed -e 's/^        //g' | sed -e 's/ /_/g' | sed -e 's/_and_/ /g'); do
        echo ${i} | sed -e 's/_/ /g'
    done | sort -u > ${GREPFILE}

    LINE=""
    REGEXP=$(grep '^License: ' ${SPEC}  | cut -d\: -f2- | sed -e 's/^        //g' | sed -e 's/ and /|/g')
    LICS=$(grep -E "^(${REGEXP})$" ${GREPFILE} )
    for LIC in ${LICS}; do
        LINE+="${LIC} and "
    done
    SORTED=$(echo ${LINE} | sed -e 's/ and$//g' | sed -e 's/^/License:        /g')
    sed -i -e "s/^License: .*/${SORTED}/g" ${SPEC}

    sed -i -e 's/ASL and 2.0/ASL 2.0/g' ${SPEC}
    sed -i -e 's/# and FIXME/# FIXME/g' ${SPEC}

    rm ${GREPFILE}
done

