#! /usr/bin/bash

for SPEC in $@; do
    echo "Reading ${SPEC}"

    if [ ! -f ${SPEC} ]; then
    echo "Cannot find ${SPEC}"
    exit 1
    fi

    GOIPATH=$(grep -P '^%global\s+goipath(0)?\s+' ${SPEC} | awk '{print $3}' | cut -d\/ -f1-3)

    if [ "${GOIPATH}" == "" ]; then
    echo "Cannot find goipath in ${SPEC}"
    exit 1
    fi

    echo "goipath in ${SPEC} is ${GOIPATH}"

    FORGEURL=$(grep -P '^%global\s+forgeurl(0)?\s+' ${SPEC} | awk '{print $3}')

    if [ "${FORGEURL}" == "" ]; then
    echo "Cannot find forgeurl in ${SPEC}"
    fi

    echo "forgeurl in ${SPEC} is ${FORGEURL}"

    TAG=$(grep -P '^%global\s+tag\s+' ${SPEC} | awk '{print $3}')

    if [ "${TAG}" == "" ]; then
        echo "Cannot find tag in ${SPEC}"
    fi

    COMMIT=$(grep -P '^%global\s+commit\s+' ${SPEC} | awk '{print $3}')

    if [ "${COMMIT}" == "" ]; then
    echo "Cannot find commit in ${SPEC}"
    fi

    PROJECT=$(echo ${GOIPATH} | rev | cut -d\/ -f1 | rev | cut -d\. -f1)

    if [ "${PROJECT}" == "" ]; then
    echo "Cannot find project in ${GOIPATH}"
    exit 1
    fi

    echo "project in ${GOIPATH} is ${PROJECT}"

    FORGE=$(echo ${FORGEURL} | rev | cut -d\/ -f1 | rev | cut -d\. -f1)

    if [ "${FORGE}" == "" ]; then
        FORGE=${PROJECT}
    fi

    echo "project in ${GOIPATH} is ${PROJECT}"

    VERSION=$(grep -P '^Version:\s+' ${SPEC} | awk '{print $2}')

    if [ "${VERSION}" == "" ]; then
    echo "Cannot find Version in ${SPEC}"
    exit 1
    fi

    echo "Version in ${SPEC} is ${VERSION}"

    SRCFILE="${PROJECT}-${VERSION}.tar.gz"
    DSTFILE="${FORGE}-${VERSION}.tar.gz"
    IPATHURL="https://${GOIPATH}"
    if [ "${FORGEURL}" != "" ]; then
        IPATHURL="${FORGEURL}"
    fi
    URL="${IPATHURL}/archive/v${VERSION}/${SRCFILE}"

    if [ "${COMMIT}" != "" ]; then
    SRCFILE="${PROJECT}-${COMMIT}.tar.gz"
    DSTFILE="${FORGE}-${COMMIT}.tar.gz"
    URL="${IPATHURL}/archive/${COMMIT}.tar.gz"
    fi

    if [ "${TAG}" != "" ]; then
        SRCFILE="${PROJECT}-${TAG}.tar.gz"
        DSTFILE="${FORGE}-${TAG}.tar.gz"
        URL="${IPATHURL}/archive/${TAG}/${SRCFILE}"
    fi

    if [ -f ${SRCFILE} ]; then
    /bin/rm ${SRCFILE}
    if [ $? -ne 0 ]; then
        echo "Problem removing ${SRCFILE}"
        exit 1
    fi
    fi

    echo "Getting ${URL}"

    wget -O ${SRCFILE} "${URL}"
    if [ $? -ne 0 ]; then
    echo "Problem downloading ${URL}"
    URL="${IPATHURL}/archive/${VERSION}/${SRCFILE}"
    echo "Trying ${URL} instead"
    echo "Getting ${URL}"

    wget -O ${SRCFILE} "${URL}"
    if [ $? -ne 0 ]; then
        echo "Problem downloading ${URL}"
        exit 1
    fi
    fi

    if [ "${FORGE}" != "${PROJECT}" ]; then
        cp -a ${SRCFILE} ${DSTFILE}
    if [ $? -ne 0 ]; then
            echo "Problem copying from ${SRCFILE} to ${DSTFILE}"
        fi
    fi
done
