#! /bin/bash

DIR=$(mktemp -d)
echo "DIR is ${DIR}"
mkdir -p ${DIR}/{provides,build,test}

for SPEC in $@; do
    echo "Reading ${SPEC}"

    if [ ! -f ${SPEC} ]; then
        echo "Cannot find ${SPEC}"
        exit 1
    fi

    BASE=$(basename ${SPEC})

    grep -E "^%global go(ipath|altipaths) " ${SPEC} | awk '{print $3}' > ${DIR}/provides/${BASE}
    grep -B 10000 -m 1 '^%if %{with check}$' ${SPEC} | grep '^BuildRequires:  golang' | cut -d '(' -f2 | cut -d ')' -f1 > ${DIR}/build/${BASE}
    grep -A 10000 -m 1 '^%if %{with check}$' ${SPEC} | grep '^BuildRequires:  golang' | cut -d '(' -f2 | cut -d ')' -f1 > ${DIR}/test/${BASE}

done

for BASE in ${DIR}/provides/*; do
    grep -f ${BASE} ${DIR}/build/*
done

