#! /bin/bash

for SPEC in $@; do
    echo "Reading ${SPEC}"

    if [ ! -f ${SPEC} ]; then
        echo "Cannot find ${SPEC}"
        exit 1
    fi

    grep -q '^%build$' ${SPEC}
    if [ $? -ne 0 ]; then
        continue
    fi

    IPATH=$(grep "^%global goipath " ${SPEC} | awk '{print $3}')
    TYPE=$(grep "^${IPATH}," ../goipaths.txt | cut -d, -f10)
    if [ "${TYPE}" == "command" ]; then
        continue
    fi

    TMPFILE1=$(mktemp)
    TMPFILE2=$(mktemp)

    grep -B 10000 '^%build$' ${SPEC} | grep -v '^%build$' > ${TMPFILE1}
    grep -A 10000 '^%install$' ${SPEC} | grep -v '^install ' | grep -v '^%{_bindir}/\*$' > ${TMPFILE2}
    cat ${TMPFILE1} ${TMPFILE2} > ${SPEC}

    rm ${TMPFILE1}
    rm ${TMPFILE2}

done
