# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/rboyer/safeio
%global goipath         github.com/rboyer/safeio
Version:                0.2.1

%gometa

%global common_description %{expand:
Provides functions to perform atomic, fsync-safe disk operations.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Provides functions to perform atomic, fsync-safe disk operations

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

