# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/golang/sync
%global goipath         golang.org/x/sync
%global forgeurl        https://github.com/golang/sync
%global commit          036812b2e83c0ddf193dd5a34e034151da389d09

%gometa

%global common_description %{expand:
[mirror] concurrency primitives.}

%global golicenses      LICENSE PATENTS
%global godocs          AUTHORS CONTRIBUTING.md CONTRIBUTORS README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        [mirror] concurrency primitives

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

