# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/aerospike/aerospike-client-go
%global goipath         github.com/aerospike/aerospike-client-go
Version:                4.5.2

%gometa

%global common_description %{expand:
Package aerospike provides a client to connect and interact with an Aerospike
cluster. This is the official Go implementation of the Aerospike Client.}

%global golicenses      LICENSE pkg/bcrypt/LICENSE
%global godocs          docs examples CHANGELOG.md README.md\\\
                        pkg/bcrypt/README tools/benchmark/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package aerospike provides a client to connect and interact with an Aerospike cluster

# Upstream license specification: Apache-2.0 and BSD-3-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/yuin/gopher-lua)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sync/semaphore)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/onsi/ginkgo)
BuildRequires:  golang(github.com/onsi/gomega)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in tools/asinfo tools/benchmark tools/cli; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE pkg/bcrypt/LICENSE
%doc docs examples CHANGELOG.md README.md pkg/bcrypt/README
%doc tools/benchmark/README.md
%{_bindir}/*

%gopkgfiles

%changelog

