# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/matryer/resync
%global goipath         github.com/matryer/resync
%global commit          d39c09a11215c84aab0b65e323fc47dd6e276af1

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

