# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/go-connlimit
%global goipath         github.com/hashicorp/go-connlimit
Version:                0.3.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE NOTICE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

