# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/rsc/letsencrypt
%global goipath         rsc.io/letsencrypt
%global forgeurl        https://github.com/rsc/letsencrypt
Version:                0.0.3

%gometa

%global common_description %{expand:
Manage TLS certificates automatically via LetsEncrypt.org.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Manage TLS certificates automatically via LetsEncrypt.org

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

