# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/dgrijalva/jwt-go
%global goipath         github.com/dgrijalva/jwt-go/v4
%global forgeurl        https://github.com/dgrijalva/jwt-go
Version:                4.0.0~preview1

%gometa
%global extractdir      jwt-go-4.0.0-preview1

%global common_description %{expand:
Package jwt is a Go implementation of JSON Web Tokens:
http://self-issued.info/docs/draft-jones-json-web-token.html See README.md for
more info.}

%global golicenses      LICENSE
%global godocs          MIGRATION_GUIDE.md README.md VERSION_HISTORY.md\\\
                        README-cmd-jwt.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package jwt is a Go implementation of JSON Web Tokens: http://self-issued

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
mv cmd/jwt/README.md README-cmd-jwt.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc MIGRATION_GUIDE.md README.md VERSION_HISTORY.md README-cmd-jwt.md

%gopkgfiles

%changelog

