# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/influxdata/changelog
%global goipath         github.com/influxdata/changelog
Version:                1.1.0

%gometa

%global common_description %{expand:
Manage a changelog using git/github metadata.}

Name:           %{goname}
Release:        1%{?dist}
Summary:        Manage a changelog using git/github metadata

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/Masterminds/semver)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(gopkg.in/src-d/go-git.v4)
BuildRequires:  golang(gopkg.in/src-d/go-git.v4/plumbing)
BuildRequires:  golang(gopkg.in/src-d/go-git.v4/plumbing/object)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/changelog %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%{_bindir}/*

%gopkgfiles

%changelog

