# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/beego/goyaml2
%global goipath         github.com/beego/goyaml2
%global commit          5545475820ddd4db3f90a4900d44b65d077d702d

%gometa

%global common_description %{expand:
YAML for Golang.}

%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        YAML for Golang

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/wendal/errors)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

