# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/cenkalti/backoff
%global goipath         github.com/cenkalti/backoff/v3
%global forgeurl        https://github.com/cenkalti/backoff
Version:                3.2.2

%gometa

%global common_description %{expand:
⏱ The exponential backoff algorithm in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        ⏱ The exponential backoff algorithm in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

