# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/go-kms-wrapping
%global goipath         github.com/hashicorp/go-kms-wrapping/entropy
%global forgeurl        https://github.com/hashicorp/go-kms-wrapping
Version:                0.1.0
%global tag             entropy/v0.1.0
%global commit          5bf905ee4d7d5a98dd57ca2dc7305c9be9087ac3

%gometa

%global common_description %{expand:
KMS wrapping libraries split out from Vault.}

%global golicenses      LICENSE
%global godocs          README.md entropy/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        KMS wrapping libraries split out from Vault

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/kms/apiv1)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/providers)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/services/kms)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/kms)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/kms/kmsiface)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure/auth)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/to)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/hashicorp/go-cleanhttp)
BuildRequires:  golang(github.com/hashicorp/go-hclog)
BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/hashicorp/vault/api)
BuildRequires:  golang(github.com/hashicorp/vault/sdk/helper/awsutil)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/common)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/common/auth)
BuildRequires:  golang(github.com/oracle/oci-go-sdk/keymanagement)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/kms/v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

