# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/vault
%global goipath         github.com/hashicorp/vault/sdk
%global forgeurl        https://github.com/hashicorp/vault
Version:                0.2.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE LICENSE-website.md
%global godocs          CHANGELOG.md README.md SPEC-api.md README-website.md\\\
                        version-website.txt docs robots-website-source.txt\\\
                        examples\\\
                        use-cases.html-website-source-intro.markdown\\\
                        index.html-website-source-intro.markdown\\\
                        acl.html-website-source-intro-getting-started.md\\\
                        authentication.html-website-source-intro-getting-started.md\\\
                        deploy.html-website-source-intro-getting-started.md\\\
                        dev-server.html-website-source-intro-getting-started.md\\\
                        dynamic-secrets.html-website-source-intro-getting-started.md\\\
                        first-secret.html-website-source-intro-getting-started.md\\\
                        help.html-website-source-intro-getting-started.md\\\
                        install.html-website-source-intro-getting-started.md\\\
                        next-steps.html-website-source-intro-getting-started.md\\\
                        secret-backends.html-website-source-intro-getting-started.md\\\
                        dropbox.html-website-source-intro-vs.md\\\
                        index.html-website-source-intro-vs.markdown\\\
                        chef-puppet-etc.html-website-source-intro-vs.md\\\
                        consul.html-website-source-intro-vs.md\\\
                        custom.html-website-source-intro-vs.markdown\\\
                        hsm.html-website-source-intro-vs.md\\\
                        keywhiz.html-website-source-intro-vs.md\\\
                        kms.html-website-source-intro-vs.md\\\
                        README-terraform-aws.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: BSD-3-Clause and MIT and MPL-2.0
License:        BSD and MIT and MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/armon/go-metrics)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/coreos/go-etcd/etcd)
BuildRequires:  golang(github.com/fatih/structs)
BuildRequires:  golang(github.com/go-ldap/ldap)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/gocql/gocql)
BuildRequires:  golang(github.com/google/go-github/github)
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/aws)
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/gen/iam)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-syslog)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/hashicorp/hcl)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl)
BuildRequires:  golang(github.com/hashicorp/logutils)
BuildRequires:  golang(github.com/kardianos/osext)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/copystructure)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/ryanuber/columnize)
BuildRequires:  golang(github.com/samuel/go-zookeeper/zk)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)
BuildRequires:  golang(golang.org/x/oauth2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/gen/ec2)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv website/LICENSE.md LICENSE-website.md
mv api/SPEC.md SPEC-api.md
mv website/README.md README-website.md
mv website/version.txt version-website.txt
mv website/source/robots.txt robots-website-source.txt
mv website/source/intro/use-cases.html.markdown use-cases.html-website-source-intro.markdown
mv website/source/intro/index.html.markdown index.html-website-source-intro.markdown
mv website/source/intro/getting-started/acl.html.md acl.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/authentication.html.md authentication.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/deploy.html.md deploy.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/dev-server.html.md dev-server.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/dynamic-secrets.html.md dynamic-secrets.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/first-secret.html.md first-secret.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/help.html.md help.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/install.html.md install.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/next-steps.html.md next-steps.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/secret-backends.html.md secret-backends.html-website-source-intro-getting-started.md
mv website/source/intro/vs/dropbox.html.md dropbox.html-website-source-intro-vs.md
mv website/source/intro/vs/index.html.markdown index.html-website-source-intro-vs.markdown
mv website/source/intro/vs/chef-puppet-etc.html.md chef-puppet-etc.html-website-source-intro-vs.md
mv website/source/intro/vs/consul.html.md consul.html-website-source-intro-vs.md
mv website/source/intro/vs/custom.html.markdown custom.html-website-source-intro-vs.markdown
mv website/source/intro/vs/hsm.html.md hsm.html-website-source-intro-vs.md
mv website/source/intro/vs/keywhiz.html.md keywhiz.html-website-source-intro-vs.md
mv website/source/intro/vs/kms.html.md kms.html-website-source-intro-vs.md
mv terraform/aws/README.md README-terraform-aws.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-website.md
%doc CHANGELOG.md README.md SPEC-api.md README-website.md version-website.txt
%doc docs robots-website-source.txt examples
%doc use-cases.html-website-source-intro.markdown
%doc index.html-website-source-intro.markdown
%doc acl.html-website-source-intro-getting-started.md
%doc authentication.html-website-source-intro-getting-started.md
%doc deploy.html-website-source-intro-getting-started.md
%doc dev-server.html-website-source-intro-getting-started.md
%doc dynamic-secrets.html-website-source-intro-getting-started.md
%doc first-secret.html-website-source-intro-getting-started.md
%doc help.html-website-source-intro-getting-started.md
%doc install.html-website-source-intro-getting-started.md
%doc next-steps.html-website-source-intro-getting-started.md
%doc secret-backends.html-website-source-intro-getting-started.md
%doc dropbox.html-website-source-intro-vs.md
%doc index.html-website-source-intro-vs.markdown
%doc chef-puppet-etc.html-website-source-intro-vs.md
%doc consul.html-website-source-intro-vs.md
%doc custom.html-website-source-intro-vs.markdown
%doc hsm.html-website-source-intro-vs.md keywhiz.html-website-source-intro-vs.md
%doc kms.html-website-source-intro-vs.md README-terraform-aws.md

%gopkgfiles

%changelog

