# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mdlayher/arp
%global goipath         github.com/mdlayher/arp
%global commit          f72070a231fc79cef00154e99b3d5a06be72398d

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE.md
%global godocs          README.md README-cmd-arpc.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mdlayher/ethernet)
BuildRequires:  golang(github.com/mdlayher/raw)

%description
%{common_description}

%gopkg

%prep
%goprep
mv cmd/arpc/README.md README-cmd-arpc.md

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc README.md README-cmd-arpc.md
%{_bindir}/*

%gopkgfiles

%changelog

