# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/cloudflare/golz4
%global goipath         github.com/cloudflare/golz4
%global commit          ef862a3cdc58a6f1fee4e3af3d44fbe279194cde

%gometa

%global common_description %{expand:
Golang interface to LZ4 compression.}

%global golicenses      LICENSE
%global godocs          README.md sample.txt

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Golang interface to LZ4 compression

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

