# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/go-redis/redis
%global goipath         github.com/go-redis/redis/v7
%global forgeurl        https://github.com/go-redis/redis
Version:                7.4.0

%gometa

%global common_description %{expand:
Package redis implements a Redis client.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package redis implements a Redis client

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/onsi/ginkgo)
BuildRequires:  golang(github.com/onsi/gomega)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

