# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/go-stomp/stomp
%global goipath         github.com/go-stomp/stomp
Version:                2.1.4

%gometa

%global common_description %{expand:
Go language library for STOMP protocol.}

%global golicenses      LICENSE.txt
%global godocs          examples AUTHORS.md README.md breaking_changes.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go language library for STOMP protocol

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(gopkg.in/check.v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck -r .*server.*
%endif

%files
%license LICENSE.txt
%doc examples AUTHORS.md README.md breaking_changes.md

%gopkgfiles

%changelog

