# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/consul
%global goipath         github.com/hashicorp/consul
Version:                1.9.5

%gometa

%global common_description %{expand:
Consul is a distributed, highly available, and data center aware solution to
connect and configure applications across dynamic, distributed infrastructure.}

%global golicenses      LICENSE NOTICE.md ui/packages/consul-\\\
                        ui/app/utils/dom/event-target/event-target-\\\
                        shim/LICENSE ui/packages/consul-ui/lib/block-\\\
                        slots/LICENSE.md website/LICENSE.md\\\
                        website/content/api-docs/operator/license.mdx\\\
                        website/content/commands/license.mdx
%global godocs          INTERNALS.md README.md CHANGELOG.md\\\
                        .changelog/10013.txt .changelog/10023.txt\\\
                        .changelog/10025.txt .changelog/7628.txt\\\
                        .changelog/7899.txt .changelog/7970.txt\\\
                        .changelog/8158.txt .changelog/8190.txt\\\
                        .changelog/8194.txt .changelog/8211.txt\\\
                        .changelog/8216.txt .changelog/8218.txt\\\
                        .changelog/8221.txt .changelog/8222.txt\\\
                        .changelog/8268.txt .changelog/8311.txt\\\
                        .changelog/8343.txt .changelog/8371.txt\\\
                        .changelog/8458.txt .changelog/8470.txt\\\
                        .changelog/8522.txt .changelog/8537.txt\\\
                        .changelog/8545.txt .changelog/8547.txt\\\
                        .changelog/8552.txt .changelog/8560.txt\\\
                        .changelog/8569.txt .changelog/8575.txt\\\
                        .changelog/8585.txt .changelog/8588.txt\\\
                        .changelog/8596.txt .changelog/8599.txt\\\
                        .changelog/8601.txt .changelog/8602.txt\\\
                        .changelog/8603.txt .changelog/8606.txt\\\
                        .changelog/8646.txt .changelog/8685.txt\\\
                        .changelog/8694.txt .changelog/8703.txt\\\
                        .changelog/8704.txt .changelog/8726.txt\\\
                        .changelog/8731.txt .changelog/8741.txt\\\
                        .changelog/8745.txt .changelog/8746.txt\\\
                        .changelog/8747.txt .changelog/8764.txt\\\
                        .changelog/8771.txt .changelog/8774.txt\\\
                        .changelog/8781.txt .changelog/8784.txt\\\
                        .changelog/8786.txt .changelog/8787.txt\\\
                        .changelog/8788.txt .changelog/8822.txt\\\
                        .changelog/8834.txt .changelog/8839.txt\\\
                        .changelog/8846.txt .changelog/8855.txt\\\
                        .changelog/8858.txt .changelog/8875.txt\\\
                        .changelog/8877.txt .changelog/8924.txt\\\
                        .changelog/9002.txt .changelog/9007.txt\\\
                        .changelog/9008.txt .changelog/9009.txt\\\
                        .changelog/9024.txt .changelog/9036.txt\\\
                        .changelog/9042.txt .changelog/9059.txt\\\
                        .changelog/9067.txt .changelog/9081.txt\\\
                        .changelog/9088.txt .changelog/9099.txt\\\
                        .changelog/9101.txt .changelog/9103.txt\\\
                        .changelog/9113.txt .changelog/9119.txt\\\
                        .changelog/9141.txt .changelog/9142.txt\\\
                        .changelog/9151.txt .changelog/9156.txt\\\
                        .changelog/9181.txt .changelog/9186.txt\\\
                        .changelog/9191.txt .changelog/9198.txt\\\
                        .changelog/9204.txt .changelog/9207.txt\\\
                        .changelog/9229.txt .changelog/9240.txt\\\
                        .changelog/9247.txt .changelog/9254.txt\\\
                        .changelog/9262.txt .changelog/9271.txt\\\
                        .changelog/9278.txt .changelog/9284.txt\\\
                        .changelog/9296.txt .changelog/9318.txt\\\
                        .changelog/9320.txt .changelog/9351.txt\\\
                        .changelog/9366.txt .changelog/9410.txt\\\
                        .changelog/9428.txt .changelog/9432.txt\\\
                        .changelog/9440.txt .changelog/9442.txt\\\
                        .changelog/9468.txt .changelog/9485.txt\\\
                        .changelog/9487.txt .changelog/9498.txt\\\
                        .changelog/9510.txt .changelog/9512.txt\\\
                        .changelog/9513.txt .changelog/9519.txt\\\
                        .changelog/9524.txt .changelog/9527.txt\\\
                        .changelog/9528.txt .changelog/9530.txt\\\
                        .changelog/9569.txt .changelog/9585.txt\\\
                        .changelog/9589.txt .changelog/9593.txt\\\
                        .changelog/9594.txt .changelog/9626.txt\\\
                        .changelog/9650.txt .changelog/9651.txt\\\
                        .changelog/9660.txt .changelog/9683.txt\\\
                        .changelog/9689.txt .changelog/9715.txt\\\
                        .changelog/9737.txt .changelog/9738.txt\\\
                        .changelog/9749.txt .changelog/9752.txt\\\
                        .changelog/9765.txt .changelog/9772.txt\\\
                        .changelog/9806.txt .changelog/9847.txt\\\
                        .changelog/9851.txt .changelog/9901.txt\\\
                        .changelog/9923.txt .changelog/9967.txt\\\
                        .changelog/9978.txt .changelog/9979.txt\\\
                        .changelog/9980.txt .changelog/_619.txt\\\
                        .changelog/_666.txt .changelog/_683.txt\\\
                        .changelog/_745.txt .changelog/_795.txt\\\
                        .changelog/_855.txt .changelog/_8621.txt\\\
                        .changelog/_8825.txt .changelog/_8984.txt\\\
                        .changelog/changelog.tmpl api/README.md\\\
                        bench/README.md bench/results-0.2.md\\\
                        bench/results-0.3.md bench/results-0.7.1.md\\\
                        contributing/INTERNALS.md contributing/README.md\\\
                        contributing/checklist-adding-config-fields.md\\\
                        demo/vagrant-cluster/README.md sdk/README.md\\\
                        sdk/testutil/README.md terraform/README.md\\\
                        types/README.md ui/README.md ui/packages/consul-\\\
                        ui/README.md ui/packages/consul-\\\
                        ui/app/components/app-error/README.stories.mdx\\\
                        ui/packages/consul-ui/app/components/auth-\\\
                        dialog/README.mdx ui/packages/consul-\\\
                        ui/app/components/auth-form/README.mdx\\\
                        ui/packages/consul-ui/app/components/auth-\\\
                        profile/README.mdx ui/packages/consul-\\\
                        ui/app/components/consul/loader/README.mdx\\\
                        ui/packages/consul-ui/app/components/consul/lock-\\\
                        session/list/README.mdx ui/packages/consul-\\\
                        ui/app/components/consul/metadata/list/README.mdx\\\
                        ui/packages/consul-\\\
                        ui/app/components/consul/nspace/list/README.mdx\\\
                        ui/packages/consul-\\\
                        ui/app/components/consul/policy/list/README.mdx\\\
                        ui/packages/consul-\\\
                        ui/app/components/consul/role/list/README.mdx\\\
                        ui/packages/consul-\\\
                        ui/app/components/consul/token/list/README.mdx\\\
                        ui/packages/consul-ui/app/components/consul/token/rul\\\
                        eset/list/README.mdx ui/packages/consul-\\\
                        ui/app/components/copy-button/README.mdx\\\
                        ui/packages/consul-ui/app/components/data-\\\
                        collection/README.mdx ui/packages/consul-\\\
                        ui/app/components/data-sink/README.mdx\\\
                        ui/packages/consul-ui/app/components/data-\\\
                        source/README.mdx ui/packages/consul-\\\
                        ui/app/components/error-state/README.stories.mdx\\\
                        ui/packages/consul-ui/app/components/event-\\\
                        source/README.mdx ui/packages/consul-\\\
                        ui/app/components/freetext-filter/README.stories.mdx\\\
                        ui/packages/consul-ui/app/components/jwt-\\\
                        source/README.mdx ui/packages/consul-\\\
                        ui/app/components/notice/README.stories.mdx\\\
                        ui/packages/consul-ui/app/components/ref/README.mdx\\\
                        ui/packages/consul-ui/app/components/state-\\\
                        chart/README.mdx ui/packages/consul-\\\
                        ui/app/components/state/README.mdx\\\
                        ui/packages/consul-ui/app/components/toggle-\\\
                        button/README.mdx ui/packages/consul-\\\
                        ui/app/components/token-source/README.mdx\\\
                        ui/packages/consul-ui/lib/block-slots/README.md\\\
                        ui/packages/consul-ui/mock-api/README.md\\\
                        ui/packages/consul-ui/public/robots.txt\\\
                        website/README.md docs website/content/security.mdx\\\
                        website/content/api-docs/acl-legacy.mdx\\\
                        website/content/api-docs/coordinate.mdx\\\
                        website/content/api-docs/discovery-chain.mdx\\\
                        website/content/api-docs/event.mdx\\\
                        website/content/api-docs/index.mdx\\\
                        website/content/api-docs/kv.mdx website/content/api-\\\
                        docs/libraries-and-sdks.mdx website/content/api-\\\
                        docs/query.mdx website/content/api-docs/session.mdx\\\
                        website/content/api-docs/snapshot.mdx\\\
                        website/content/api-docs/status.mdx\\\
                        website/content/api-docs/txn.mdx website/content/api-\\\
                        docs/config.mdx website/content/api-\\\
                        docs/namespaces.mdx website/content/api-\\\
                        docs/catalog.mdx website/content/api-docs/health.mdx\\\
                        website/content/api-docs/acl/auth-methods.mdx\\\
                        website/content/api-docs/acl/binding-rules.mdx\\\
                        website/content/api-docs/acl/legacy.mdx\\\
                        website/content/api-docs/acl/policies.mdx\\\
                        website/content/api-docs/acl/roles.mdx\\\
                        website/content/api-docs/acl/tokens.mdx\\\
                        website/content/api-docs/acl/index.mdx\\\
                        website/content/api-docs/agent/connect.mdx\\\
                        website/content/api-docs/agent/index.mdx\\\
                        website/content/api-docs/agent/check.mdx\\\
                        website/content/api-docs/agent/service.mdx\\\
                        website/content/api-docs/connect/index.mdx\\\
                        website/content/api-docs/connect/intentions.mdx\\\
                        website/content/api-docs/connect/ca.mdx\\\
                        website/content/api-docs/features/blocking.mdx\\\
                        website/content/api-docs/features/caching.mdx\\\
                        website/content/api-docs/features/consistency.mdx\\\
                        website/content/api-docs/features/filtering.mdx\\\
                        website/content/api-docs/operator/area.mdx\\\
                        website/content/api-docs/operator/autopilot.mdx\\\
                        website/content/api-docs/operator/index.mdx\\\
                        website/content/api-docs/operator/keyring.mdx\\\
                        website/content/api-docs/operator/raft.mdx\\\
                        website/content/api-docs/operator/segment.mdx\\\
                        website/content/commands/agent.mdx\\\
                        website/content/commands/debug.mdx\\\
                        website/content/commands/event.mdx\\\
                        website/content/commands/exec.mdx\\\
                        website/content/commands/force-leave.mdx\\\
                        website/content/commands/index.mdx\\\
                        website/content/commands/info.mdx\\\
                        website/content/commands/join.mdx\\\
                        website/content/commands/keygen.mdx\\\
                        website/content/commands/keyring.mdx\\\
                        website/content/commands/leave.mdx\\\
                        website/content/commands/lock.mdx\\\
                        website/content/commands/login.mdx\\\
                        website/content/commands/logout.mdx\\\
                        website/content/commands/maint.mdx\\\
                        website/content/commands/members.mdx\\\
                        website/content/commands/monitor.mdx\\\
                        website/content/commands/reload.mdx\\\
                        website/content/commands/rtt.mdx\\\
                        website/content/commands/validate.mdx\\\
                        website/content/commands/version.mdx\\\
                        website/content/commands/watch.mdx\\\
                        website/content/commands/acl/bootstrap.mdx\\\
                        website/content/commands/acl/index.mdx\\\
                        website/content/commands/acl/set-agent-token.mdx\\\
                        website/content/commands/acl/translate-rules.mdx\\\
                        website/content/commands/acl/auth-method/create.mdx\\\
                        website/content/commands/acl/auth-method/delete.mdx\\\
                        website/content/commands/acl/auth-method/index.mdx\\\
                        website/content/commands/acl/auth-method/list.mdx\\\
                        website/content/commands/acl/auth-method/read.mdx\\\
                        website/content/commands/acl/auth-method/update.mdx\\\
                        website/content/commands/acl/binding-rule/create.mdx\\\
                        website/content/commands/acl/binding-rule/delete.mdx\\\
                        website/content/commands/acl/binding-rule/index.mdx\\\
                        website/content/commands/acl/binding-rule/list.mdx\\\
                        website/content/commands/acl/binding-rule/read.mdx\\\
                        website/content/commands/acl/binding-rule/update.mdx\\\
                        website/content/commands/acl/policy/create.mdx\\\
                        website/content/commands/acl/policy/delete.mdx\\\
                        website/content/commands/acl/policy/index.mdx\\\
                        website/content/commands/acl/policy/list.mdx\\\
                        website/content/commands/acl/policy/read.mdx\\\
                        website/content/commands/acl/policy/update.mdx\\\
                        website/content/commands/acl/role/create.mdx\\\
                        website/content/commands/acl/role/delete.mdx\\\
                        website/content/commands/acl/role/index.mdx\\\
                        website/content/commands/acl/role/list.mdx\\\
                        website/content/commands/acl/role/read.mdx\\\
                        website/content/commands/acl/role/update.mdx\\\
                        website/content/commands/acl/token/clone.mdx\\\
                        website/content/commands/acl/token/create.mdx\\\
                        website/content/commands/acl/token/delete.mdx\\\
                        website/content/commands/acl/token/index.mdx\\\
                        website/content/commands/acl/token/list.mdx\\\
                        website/content/commands/acl/token/read.mdx\\\
                        website/content/commands/acl/token/update.mdx\\\
                        website/content/commands/catalog/datacenters.mdx\\\
                        website/content/commands/catalog/index.mdx\\\
                        website/content/commands/catalog/nodes.mdx\\\
                        website/content/commands/catalog/services.mdx\\\
                        website/content/commands/config/index.mdx\\\
                        website/content/commands/config/write.mdx\\\
                        website/content/commands/config/delete.mdx\\\
                        website/content/commands/config/list.mdx\\\
                        website/content/commands/config/read.mdx\\\
                        website/content/commands/connect/expose.mdx\\\
                        website/content/commands/connect/proxy.mdx\\\
                        website/content/commands/connect/ca.mdx\\\
                        website/content/commands/connect/envoy.mdx\\\
                        website/content/commands/connect/index.mdx\\\
                        website/content/commands/intention/check.mdx\\\
                        website/content/commands/intention/create.mdx\\\
                        website/content/commands/intention/delete.mdx\\\
                        website/content/commands/intention/get.mdx\\\
                        website/content/commands/intention/index.mdx\\\
                        website/content/commands/intention/list.mdx\\\
                        website/content/commands/intention/match.mdx\\\
                        website/content/commands/kv/delete.mdx\\\
                        website/content/commands/kv/export.mdx\\\
                        website/content/commands/kv/get.mdx\\\
                        website/content/commands/kv/index.mdx\\\
                        website/content/commands/kv/put.mdx\\\
                        website/content/commands/kv/import.mdx\\\
                        website/content/commands/namespace/create.mdx\\\
                        website/content/commands/namespace/delete.mdx\\\
                        website/content/commands/namespace/index.mdx\\\
                        website/content/commands/namespace/list.mdx\\\
                        website/content/commands/namespace/read.mdx\\\
                        website/content/commands/namespace/update.mdx\\\
                        website/content/commands/namespace/write.mdx\\\
                        website/content/commands/operator/area.mdx\\\
                        website/content/commands/operator/autopilot.mdx\\\
                        website/content/commands/operator/index.mdx\\\
                        website/content/commands/operator/raft.mdx\\\
                        website/content/commands/services/deregister.mdx\\\
                        website/content/commands/services/index.mdx\\\
                        website/content/commands/services/register.mdx\\\
                        website/content/commands/snapshot/index.mdx\\\
                        website/content/commands/snapshot/restore.mdx\\\
                        website/content/commands/snapshot/save.mdx\\\
                        website/content/commands/snapshot/agent.mdx\\\
                        website/content/commands/snapshot/inspect.mdx\\\
                        website/content/commands/tls/ca.mdx\\\
                        website/content/commands/tls/cert.mdx\\\
                        website/content/commands/tls/index.mdx website/conten\\\
                        t/partials/http_api_namespace_options.mdx\\\
                        website/content/partials/http_api_options_client.mdx\\\
                        website/content/partials/http_api_options_server.mdx \\\
                        website/content/partials/jwt_claim_mapping_details.md\\\
                        x website/content/partials/jwt_or_oidc.mdx docs\\\
                        website/public/robots.txt website/raw-assets/README

Name:           %{goname}
Release:        1%{?dist}
Summary:        Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure

# Upstream license specification: MIT and MPL-2.0
License:        MIT and MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/armon/circbuf)
BuildRequires:  golang(github.com/armon/go-metrics)
BuildRequires:  golang(github.com/armon/go-metrics/circonus)
BuildRequires:  golang(github.com/armon/go-metrics/datadog)
BuildRequires:  golang(github.com/armon/go-metrics/prometheus)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/acmpca)
BuildRequires:  golang(github.com/coredns/coredns/plugin/pkg/dnsutil)
BuildRequires:  golang(github.com/coreos/go-oidc)
BuildRequires:  golang(github.com/docker/go-connections/sockets)
BuildRequires:  golang(github.com/elazarl/go-bindata-assetfs)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/auth)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/cluster)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/core)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/endpoint)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/listener)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/api/v2/route)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/filter/http/rbac/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/filter/network/http_connection_manager/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/filter/network/rbac/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/filter/network/tcp_proxy/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/config/rbac/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/service/auth/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/type)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/envoy/type/matcher)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/pkg/conversion)
BuildRequires:  golang(github.com/envoyproxy/go-control-plane/pkg/wellknown)
BuildRequires:  golang(github.com/gogo/protobuf/gogoproto)
BuildRequires:  golang(github.com/gogo/protobuf/types)
BuildRequires:  golang(github.com/golang/protobuf/jsonpb)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/struct)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/wrappers)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/go-bexpr)
BuildRequires:  golang(github.com/hashicorp/go-checkpoint)
BuildRequires:  golang(github.com/hashicorp/go-cleanhttp)
BuildRequires:  golang(github.com/hashicorp/go-connlimit)
BuildRequires:  golang(github.com/hashicorp/go-discover)
BuildRequires:  golang(github.com/hashicorp/go-discover/provider/k8s)
BuildRequires:  golang(github.com/hashicorp/go-hclog)
BuildRequires:  golang(github.com/hashicorp/go-memdb)
BuildRequires:  golang(github.com/hashicorp/go-msgpack/codec)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-raftchunking)
BuildRequires:  golang(github.com/hashicorp/go-rootcerts)
BuildRequires:  golang(github.com/hashicorp/go-sockaddr/template)
BuildRequires:  golang(github.com/hashicorp/go-syslog)
BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/hashicorp/go-version)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/hashicorp/hcl)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/ast)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/printer)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/token)
BuildRequires:  golang(github.com/hashicorp/hil)
BuildRequires:  golang(github.com/hashicorp/hil/ast)
BuildRequires:  golang(github.com/hashicorp/memberlist)
BuildRequires:  golang(github.com/hashicorp/net-rpc-msgpackrpc)
BuildRequires:  golang(github.com/hashicorp/raft)
BuildRequires:  golang(github.com/hashicorp/raft-autopilot)
BuildRequires:  golang(github.com/hashicorp/raft-boltdb)
BuildRequires:  golang(github.com/hashicorp/serf/coordinate)
BuildRequires:  golang(github.com/hashicorp/serf/serf)
BuildRequires:  golang(github.com/hashicorp/vault/api)
BuildRequires:  golang(github.com/hashicorp/yamux)
BuildRequires:  golang(github.com/imdario/mergo)
BuildRequires:  golang(github.com/kr/text)
BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/copystructure)
BuildRequires:  golang(github.com/mitchellh/go-testing-interface)
BuildRequires:  golang(github.com/mitchellh/hashstructure)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/pointerstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/NYTimes/gziphandler)
BuildRequires:  golang(github.com/patrickmn/go-cache)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus/promhttp)
BuildRequires:  golang(github.com/rboyer/safeio)
BuildRequires:  golang(github.com/ryanuber/columnize)
BuildRequires:  golang(github.com/shirou/gopsutil/v3/cpu)
BuildRequires:  golang(github.com/shirou/gopsutil/v3/disk)
BuildRequires:  golang(github.com/shirou/gopsutil/v3/host)
BuildRequires:  golang(github.com/shirou/gopsutil/v3/mem)
BuildRequires:  golang(github.com/stretchr/testify/mock)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(golang.org/x/crypto/blake2b)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sync/singleflight)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/time/rate)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/health/grpc_health_v1)
BuildRequires:  golang(google.golang.org/grpc/keepalive)
BuildRequires:  golang(google.golang.org/grpc/metadata)
BuildRequires:  golang(google.golang.org/grpc/resolver)
BuildRequires:  golang(google.golang.org/grpc/stats)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(gopkg.in/square/go-jose.v2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2/jwt)
BuildRequires:  golang(k8s.io/api/authentication/v1)
BuildRequires:  golang(k8s.io/api/core/v1)
BuildRequires:  golang(k8s.io/apimachinery/pkg/apis/meta/v1)
BuildRequires:  golang(k8s.io/apimachinery/pkg/types)
BuildRequires:  golang(k8s.io/client-go/kubernetes)
BuildRequires:  golang(k8s.io/client-go/kubernetes/typed/authentication/v1)
BuildRequires:  golang(k8s.io/client-go/kubernetes/typed/core/v1)
BuildRequires:  golang(k8s.io/client-go/rest)
BuildRequires:  golang(k8s.io/client-go/util/cert)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(github.com/google/gofuzz)
BuildRequires:  golang(github.com/google/tcpproxy)
BuildRequires:  golang(github.com/hashicorp/go-raftchunking/types)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(golang.org/x/net/html)
BuildRequires:  golang(google.golang.org/grpc/health)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/consul %{goipath}
for cmd in command/maint connect/certgen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE.md
%license ui/packages/consul-ui/app/utils/dom/event-target/event-target-shim/LICENSE
%license ui/packages/consul-ui/lib/block-slots/LICENSE.md website/LICENSE.md
%license website/content/api-docs/operator/license.mdx
%license website/content/commands/license.mdx
%doc INTERNALS.md README.md CHANGELOG.md .changelog/10013.txt
%doc .changelog/10023.txt .changelog/10025.txt .changelog/7628.txt
%doc .changelog/7899.txt .changelog/7970.txt .changelog/8158.txt
%doc .changelog/8190.txt .changelog/8194.txt .changelog/8211.txt
%doc .changelog/8216.txt .changelog/8218.txt .changelog/8221.txt
%doc .changelog/8222.txt .changelog/8268.txt .changelog/8311.txt
%doc .changelog/8343.txt .changelog/8371.txt .changelog/8458.txt
%doc .changelog/8470.txt .changelog/8522.txt .changelog/8537.txt
%doc .changelog/8545.txt .changelog/8547.txt .changelog/8552.txt
%doc .changelog/8560.txt .changelog/8569.txt .changelog/8575.txt
%doc .changelog/8585.txt .changelog/8588.txt .changelog/8596.txt
%doc .changelog/8599.txt .changelog/8601.txt .changelog/8602.txt
%doc .changelog/8603.txt .changelog/8606.txt .changelog/8646.txt
%doc .changelog/8685.txt .changelog/8694.txt .changelog/8703.txt
%doc .changelog/8704.txt .changelog/8726.txt .changelog/8731.txt
%doc .changelog/8741.txt .changelog/8745.txt .changelog/8746.txt
%doc .changelog/8747.txt .changelog/8764.txt .changelog/8771.txt
%doc .changelog/8774.txt .changelog/8781.txt .changelog/8784.txt
%doc .changelog/8786.txt .changelog/8787.txt .changelog/8788.txt
%doc .changelog/8822.txt .changelog/8834.txt .changelog/8839.txt
%doc .changelog/8846.txt .changelog/8855.txt .changelog/8858.txt
%doc .changelog/8875.txt .changelog/8877.txt .changelog/8924.txt
%doc .changelog/9002.txt .changelog/9007.txt .changelog/9008.txt
%doc .changelog/9009.txt .changelog/9024.txt .changelog/9036.txt
%doc .changelog/9042.txt .changelog/9059.txt .changelog/9067.txt
%doc .changelog/9081.txt .changelog/9088.txt .changelog/9099.txt
%doc .changelog/9101.txt .changelog/9103.txt .changelog/9113.txt
%doc .changelog/9119.txt .changelog/9141.txt .changelog/9142.txt
%doc .changelog/9151.txt .changelog/9156.txt .changelog/9181.txt
%doc .changelog/9186.txt .changelog/9191.txt .changelog/9198.txt
%doc .changelog/9204.txt .changelog/9207.txt .changelog/9229.txt
%doc .changelog/9240.txt .changelog/9247.txt .changelog/9254.txt
%doc .changelog/9262.txt .changelog/9271.txt .changelog/9278.txt
%doc .changelog/9284.txt .changelog/9296.txt .changelog/9318.txt
%doc .changelog/9320.txt .changelog/9351.txt .changelog/9366.txt
%doc .changelog/9410.txt .changelog/9428.txt .changelog/9432.txt
%doc .changelog/9440.txt .changelog/9442.txt .changelog/9468.txt
%doc .changelog/9485.txt .changelog/9487.txt .changelog/9498.txt
%doc .changelog/9510.txt .changelog/9512.txt .changelog/9513.txt
%doc .changelog/9519.txt .changelog/9524.txt .changelog/9527.txt
%doc .changelog/9528.txt .changelog/9530.txt .changelog/9569.txt
%doc .changelog/9585.txt .changelog/9589.txt .changelog/9593.txt
%doc .changelog/9594.txt .changelog/9626.txt .changelog/9650.txt
%doc .changelog/9651.txt .changelog/9660.txt .changelog/9683.txt
%doc .changelog/9689.txt .changelog/9715.txt .changelog/9737.txt
%doc .changelog/9738.txt .changelog/9749.txt .changelog/9752.txt
%doc .changelog/9765.txt .changelog/9772.txt .changelog/9806.txt
%doc .changelog/9847.txt .changelog/9851.txt .changelog/9901.txt
%doc .changelog/9923.txt .changelog/9967.txt .changelog/9978.txt
%doc .changelog/9979.txt .changelog/9980.txt .changelog/_619.txt
%doc .changelog/_666.txt .changelog/_683.txt .changelog/_745.txt
%doc .changelog/_795.txt .changelog/_855.txt .changelog/_8621.txt
%doc .changelog/_8825.txt .changelog/_8984.txt .changelog/changelog.tmpl
%doc api/README.md bench/README.md bench/results-0.2.md bench/results-0.3.md
%doc bench/results-0.7.1.md contributing/INTERNALS.md contributing/README.md
%doc contributing/checklist-adding-config-fields.md
%doc demo/vagrant-cluster/README.md sdk/README.md sdk/testutil/README.md
%doc terraform/README.md types/README.md ui/README.md
%doc ui/packages/consul-ui/README.md
%doc ui/packages/consul-ui/app/components/app-error/README.stories.mdx
%doc ui/packages/consul-ui/app/components/auth-dialog/README.mdx
%doc ui/packages/consul-ui/app/components/auth-form/README.mdx
%doc ui/packages/consul-ui/app/components/auth-profile/README.mdx
%doc ui/packages/consul-ui/app/components/consul/loader/README.mdx
%doc ui/packages/consul-ui/app/components/consul/lock-session/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/metadata/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/nspace/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/policy/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/role/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/token/list/README.mdx
%doc ui/packages/consul-ui/app/components/consul/token/ruleset/list/README.mdx
%doc ui/packages/consul-ui/app/components/copy-button/README.mdx
%doc ui/packages/consul-ui/app/components/data-collection/README.mdx
%doc ui/packages/consul-ui/app/components/data-sink/README.mdx
%doc ui/packages/consul-ui/app/components/data-source/README.mdx
%doc ui/packages/consul-ui/app/components/error-state/README.stories.mdx
%doc ui/packages/consul-ui/app/components/event-source/README.mdx
%doc ui/packages/consul-ui/app/components/freetext-filter/README.stories.mdx
%doc ui/packages/consul-ui/app/components/jwt-source/README.mdx
%doc ui/packages/consul-ui/app/components/notice/README.stories.mdx
%doc ui/packages/consul-ui/app/components/ref/README.mdx
%doc ui/packages/consul-ui/app/components/state-chart/README.mdx
%doc ui/packages/consul-ui/app/components/state/README.mdx
%doc ui/packages/consul-ui/app/components/toggle-button/README.mdx
%doc ui/packages/consul-ui/app/components/token-source/README.mdx
%doc ui/packages/consul-ui/lib/block-slots/README.md
%doc ui/packages/consul-ui/mock-api/README.md
%doc ui/packages/consul-ui/public/robots.txt website/README.md docs
%doc website/content/security.mdx website/content/api-docs/acl-legacy.mdx
%doc website/content/api-docs/coordinate.mdx
%doc website/content/api-docs/discovery-chain.mdx
%doc website/content/api-docs/event.mdx website/content/api-docs/index.mdx
%doc website/content/api-docs/kv.mdx
%doc website/content/api-docs/libraries-and-sdks.mdx
%doc website/content/api-docs/query.mdx website/content/api-docs/session.mdx
%doc website/content/api-docs/snapshot.mdx website/content/api-docs/status.mdx
%doc website/content/api-docs/txn.mdx website/content/api-docs/config.mdx
%doc website/content/api-docs/namespaces.mdx
%doc website/content/api-docs/catalog.mdx website/content/api-docs/health.mdx
%doc website/content/api-docs/acl/auth-methods.mdx
%doc website/content/api-docs/acl/binding-rules.mdx
%doc website/content/api-docs/acl/legacy.mdx
%doc website/content/api-docs/acl/policies.mdx
%doc website/content/api-docs/acl/roles.mdx
%doc website/content/api-docs/acl/tokens.mdx
%doc website/content/api-docs/acl/index.mdx
%doc website/content/api-docs/agent/connect.mdx
%doc website/content/api-docs/agent/index.mdx
%doc website/content/api-docs/agent/check.mdx
%doc website/content/api-docs/agent/service.mdx
%doc website/content/api-docs/connect/index.mdx
%doc website/content/api-docs/connect/intentions.mdx
%doc website/content/api-docs/connect/ca.mdx
%doc website/content/api-docs/features/blocking.mdx
%doc website/content/api-docs/features/caching.mdx
%doc website/content/api-docs/features/consistency.mdx
%doc website/content/api-docs/features/filtering.mdx
%doc website/content/api-docs/operator/area.mdx
%doc website/content/api-docs/operator/autopilot.mdx
%doc website/content/api-docs/operator/index.mdx
%doc website/content/api-docs/operator/keyring.mdx
%doc website/content/api-docs/operator/raft.mdx
%doc website/content/api-docs/operator/segment.mdx
%doc website/content/commands/agent.mdx website/content/commands/debug.mdx
%doc website/content/commands/event.mdx website/content/commands/exec.mdx
%doc website/content/commands/force-leave.mdx website/content/commands/index.mdx
%doc website/content/commands/info.mdx website/content/commands/join.mdx
%doc website/content/commands/keygen.mdx website/content/commands/keyring.mdx
%doc website/content/commands/leave.mdx website/content/commands/lock.mdx
%doc website/content/commands/login.mdx website/content/commands/logout.mdx
%doc website/content/commands/maint.mdx website/content/commands/members.mdx
%doc website/content/commands/monitor.mdx website/content/commands/reload.mdx
%doc website/content/commands/rtt.mdx website/content/commands/validate.mdx
%doc website/content/commands/version.mdx website/content/commands/watch.mdx
%doc website/content/commands/acl/bootstrap.mdx
%doc website/content/commands/acl/index.mdx
%doc website/content/commands/acl/set-agent-token.mdx
%doc website/content/commands/acl/translate-rules.mdx
%doc website/content/commands/acl/auth-method/create.mdx
%doc website/content/commands/acl/auth-method/delete.mdx
%doc website/content/commands/acl/auth-method/index.mdx
%doc website/content/commands/acl/auth-method/list.mdx
%doc website/content/commands/acl/auth-method/read.mdx
%doc website/content/commands/acl/auth-method/update.mdx
%doc website/content/commands/acl/binding-rule/create.mdx
%doc website/content/commands/acl/binding-rule/delete.mdx
%doc website/content/commands/acl/binding-rule/index.mdx
%doc website/content/commands/acl/binding-rule/list.mdx
%doc website/content/commands/acl/binding-rule/read.mdx
%doc website/content/commands/acl/binding-rule/update.mdx
%doc website/content/commands/acl/policy/create.mdx
%doc website/content/commands/acl/policy/delete.mdx
%doc website/content/commands/acl/policy/index.mdx
%doc website/content/commands/acl/policy/list.mdx
%doc website/content/commands/acl/policy/read.mdx
%doc website/content/commands/acl/policy/update.mdx
%doc website/content/commands/acl/role/create.mdx
%doc website/content/commands/acl/role/delete.mdx
%doc website/content/commands/acl/role/index.mdx
%doc website/content/commands/acl/role/list.mdx
%doc website/content/commands/acl/role/read.mdx
%doc website/content/commands/acl/role/update.mdx
%doc website/content/commands/acl/token/clone.mdx
%doc website/content/commands/acl/token/create.mdx
%doc website/content/commands/acl/token/delete.mdx
%doc website/content/commands/acl/token/index.mdx
%doc website/content/commands/acl/token/list.mdx
%doc website/content/commands/acl/token/read.mdx
%doc website/content/commands/acl/token/update.mdx
%doc website/content/commands/catalog/datacenters.mdx
%doc website/content/commands/catalog/index.mdx
%doc website/content/commands/catalog/nodes.mdx
%doc website/content/commands/catalog/services.mdx
%doc website/content/commands/config/index.mdx
%doc website/content/commands/config/write.mdx
%doc website/content/commands/config/delete.mdx
%doc website/content/commands/config/list.mdx
%doc website/content/commands/config/read.mdx
%doc website/content/commands/connect/expose.mdx
%doc website/content/commands/connect/proxy.mdx
%doc website/content/commands/connect/ca.mdx
%doc website/content/commands/connect/envoy.mdx
%doc website/content/commands/connect/index.mdx
%doc website/content/commands/intention/check.mdx
%doc website/content/commands/intention/create.mdx
%doc website/content/commands/intention/delete.mdx
%doc website/content/commands/intention/get.mdx
%doc website/content/commands/intention/index.mdx
%doc website/content/commands/intention/list.mdx
%doc website/content/commands/intention/match.mdx
%doc website/content/commands/kv/delete.mdx
%doc website/content/commands/kv/export.mdx website/content/commands/kv/get.mdx
%doc website/content/commands/kv/index.mdx website/content/commands/kv/put.mdx
%doc website/content/commands/kv/import.mdx
%doc website/content/commands/namespace/create.mdx
%doc website/content/commands/namespace/delete.mdx
%doc website/content/commands/namespace/index.mdx
%doc website/content/commands/namespace/list.mdx
%doc website/content/commands/namespace/read.mdx
%doc website/content/commands/namespace/update.mdx
%doc website/content/commands/namespace/write.mdx
%doc website/content/commands/operator/area.mdx
%doc website/content/commands/operator/autopilot.mdx
%doc website/content/commands/operator/index.mdx
%doc website/content/commands/operator/raft.mdx
%doc website/content/commands/services/deregister.mdx
%doc website/content/commands/services/index.mdx
%doc website/content/commands/services/register.mdx
%doc website/content/commands/snapshot/index.mdx
%doc website/content/commands/snapshot/restore.mdx
%doc website/content/commands/snapshot/save.mdx
%doc website/content/commands/snapshot/agent.mdx
%doc website/content/commands/snapshot/inspect.mdx
%doc website/content/commands/tls/ca.mdx website/content/commands/tls/cert.mdx
%doc website/content/commands/tls/index.mdx
%doc website/content/partials/http_api_namespace_options.mdx
%doc website/content/partials/http_api_options_client.mdx
%doc website/content/partials/http_api_options_server.mdx
%doc website/content/partials/jwt_claim_mapping_details.mdx
%doc website/content/partials/jwt_or_oidc.mdx docs website/public/robots.txt
%doc website/raw-assets/README
%{_bindir}/*

%gopkgfiles

%changelog

