# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/etcd-io/gofail
%global goipath         github.com/etcd-io/gofail
%global commit          ad7f989257ca7de90de65657c9748a3108b1460f

%gometa

%global common_description %{expand:
gofail is a tool for enabling/disabling failpoints in go code.}

%global golicenses      LICENSE NOTICE
%global godocs          examples README.md code-of-conduct.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        gofail is a tool for enabling/disabling failpoints in go code

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/gofail %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE
%doc examples README.md code-of-conduct.md
%{_bindir}/*

%gopkgfiles

%changelog

