# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/fsnotify/fsnotify
%global goipath         github.com/fsnotify/fsnotify
Version:                1.4.9

%gometa

%global common_description %{expand:
Cross-platform file system notifications for Go.}

%global golicenses      LICENSE
%global godocs          AUTHORS CHANGELOG.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Cross-platform file system notifications for Go

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

