# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/moul/http2curl
%global goipath         github.com/moul/http2curl
Version:                1.0.0

%gometa

%global common_description %{expand:
:triangular_ruler: Convert Golang's http.Request to CURL command line.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        :triangular_ruler: Convert Golang's http.Request to CURL command line

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/smartystreets/goconvey/convey)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

