# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/caarlos0/env
%global goipath         github.com/caarlos0/env/v6
%global forgeurl        https://github.com/caarlos0/env
Version:                6.6.2

%gometa

%global common_description %{expand:
Simple lib to parse environment variables to structs.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Simple lib to parse environment variables to structs

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/matryer/is)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

