# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/tj/go-buffer
%global goipath         github.com/tj/go-buffer
Version:                1.2.0

%gometa

%global common_description %{expand:
Generic buffer for batching entries, such as log events.}

%global golicenses      LICENSE
%global godocs          History.md Readme.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Generic buffer for batching entries, such as log events

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

