# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/opencontainers/runc
%global goipath         github.com/opencontainers/runc
Version:                0.1.1

%gometa

%global common_description %{expand:
CLI tool for spawning and running containers according to the OCI
specification.}

%global golicenses      LICENSE NOTICE
%global godocs          PRINCIPLES.md CONTRIBUTING.md MAINTAINERS_GUIDE.md\\\
                        README.md README-libcontainer.md\\\
                        SPEC-libcontainer.md README-libcontainer-nsenter.md\\\
                        README-man.md runc-checkpoint.8-man.md\\\
                        runc-delete.8-man.md runc-events.8-man.md\\\
                        runc-exec.8-man.md runc-kill.8-man.md\\\
                        runc-list.8-man.md runc-pause.8-man.md\\\
                        runc-restore.8-man.md runc-resume.8-man.md\\\
                        runc-spec.8-man.md runc-start.8-man.md\\\
                        runc-state.8-man.md runc.8-man.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        CLI tool for spawning and running containers according to the OCI specification

# Upstream license specification: Apache-2.0 and BSD-2-Clause and BSD-3-Clause and MIT
License:        ASL 2.0 and BSD and MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/codegangsta/cli)
BuildRequires:  golang(github.com/coreos/go-systemd/activation)
BuildRequires:  golang(github.com/coreos/go-systemd/dbus)
BuildRequires:  golang(github.com/coreos/go-systemd/util)
BuildRequires:  golang(github.com/docker/docker/pkg/mount)
BuildRequires:  golang(github.com/docker/docker/pkg/symlink)
BuildRequires:  golang(github.com/docker/docker/pkg/term)
BuildRequires:  golang(github.com/docker/go-units)
BuildRequires:  golang(github.com/godbus/dbus)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/opencontainers/runtime-spec/specs-go)
BuildRequires:  golang(github.com/Sirupsen/logrus)
BuildRequires:  golang(github.com/syndtr/gocapability/capability)
BuildRequires:  golang(github.com/vishvananda/netlink)
BuildRequires:  golang(github.com/vishvananda/netlink/nl)

%description
%{common_description}

%gopkg

%prep
%goprep
mv libcontainer/README.md README-libcontainer.md
mv libcontainer/SPEC.md SPEC-libcontainer.md
mv libcontainer/nsenter/README.md README-libcontainer-nsenter.md
mv man/README.md README-man.md
mv man/runc-checkpoint.8.md runc-checkpoint.8-man.md
mv man/runc-delete.8.md runc-delete.8-man.md
mv man/runc-events.8.md runc-events.8-man.md
mv man/runc-exec.8.md runc-exec.8-man.md
mv man/runc-kill.8.md runc-kill.8-man.md
mv man/runc-list.8.md runc-list.8-man.md
mv man/runc-pause.8.md runc-pause.8-man.md
mv man/runc-restore.8.md runc-restore.8-man.md
mv man/runc-resume.8.md runc-resume.8-man.md
mv man/runc-spec.8.md runc-spec.8-man.md
mv man/runc-start.8.md runc-start.8-man.md
mv man/runc-state.8.md runc-state.8-man.md
mv man/runc.8.md runc.8-man.md

%build
%gobuild -o %{gobuilddir}/bin/runc %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE
%doc PRINCIPLES.md CONTRIBUTING.md MAINTAINERS_GUIDE.md README.md
%doc README-libcontainer.md SPEC-libcontainer.md README-libcontainer-nsenter.md
%doc README-man.md runc-checkpoint.8-man.md runc-delete.8-man.md
%doc runc-events.8-man.md runc-exec.8-man.md runc-kill.8-man.md
%doc runc-list.8-man.md runc-pause.8-man.md runc-restore.8-man.md
%doc runc-resume.8-man.md runc-spec.8-man.md runc-start.8-man.md
%doc runc-state.8-man.md runc.8-man.md
%{_bindir}/*

%gopkgfiles

%changelog

