# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/theupdateframework/notary
%global goipath         github.com/theupdateframework/notary
Version:                0.7.0

%gometa

%global common_description %{expand:
Notary is a project that allows anyone to have trust over arbitrary collections
of data.}

%global golicenses      LICENSE LICENSE-tuf
%global godocs          docs CODE_OF_CONDUCT.md CONTRIBUTING.md CONTRIBUTORS\\\
                        README.md CHANGELOG.md MAINTAINERS_RULES.md\\\
                        README-fixtures-compatibility.md\\\
                        README-fixtures-compatibility-notary0.1.txt\\\
                        README-migrations.md importLogic-trustmanager.md\\\
                        README-tuf.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Notary is a project that allows anyone to have trust over arbitrary collections of data

# Upstream license specification: Apache-2.0 and BSD-3-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/bugsnag/bugsnag-go)
BuildRequires:  golang(github.com/docker/distribution/context)
BuildRequires:  golang(github.com/docker/distribution/health)
BuildRequires:  golang(github.com/docker/distribution/registry/api/errcode)
BuildRequires:  golang(github.com/docker/distribution/registry/auth)
BuildRequires:  golang(github.com/docker/distribution/registry/auth/htpasswd)
BuildRequires:  golang(github.com/docker/distribution/registry/auth/token)
BuildRequires:  golang(github.com/docker/distribution/registry/client/auth)
BuildRequires:  golang(github.com/docker/distribution/registry/client/auth/challenge)
BuildRequires:  golang(github.com/docker/distribution/registry/client/transport)
BuildRequires:  golang(github.com/docker/distribution/uuid)
BuildRequires:  golang(github.com/docker/go-connections/tlsconfig)
BuildRequires:  golang(github.com/docker/go/canonical/json)
BuildRequires:  golang(github.com/dvsekhvalnov/jose2go)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/empty)
BuildRequires:  golang(github.com/gorilla/mux)
BuildRequires:  golang(github.com/jinzhu/gorm)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/Shopify/logrus-bugsnag)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(golang.org/x/crypto/ed25519)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/term)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/health)
BuildRequires:  golang(google.golang.org/grpc/health/grpc_health_v1)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/docker/distribution/registry/auth/silly)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv tuf/LICENSE LICENSE-tuf
mv fixtures/compatibility/README.md README-fixtures-compatibility.md
mv fixtures/compatibility/notary0.1/README.txt README-fixtures-compatibility-notary0.1.txt
mv migrations/README.md README-migrations.md
mv trustmanager/importLogic.md importLogic-trustmanager.md
mv tuf/README.md README-tuf.md

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-tuf
%doc docs CODE_OF_CONDUCT.md CONTRIBUTING.md CONTRIBUTORS README.md CHANGELOG.md
%doc MAINTAINERS_RULES.md README-fixtures-compatibility.md
%doc README-fixtures-compatibility-notary0.1.txt README-migrations.md
%doc importLogic-trustmanager.md README-tuf.md
%{_bindir}/*

%gopkgfiles

%changelog

