# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/raft-autopilot
%global goipath         github.com/hashicorp/raft-autopilot
Version:                0.1.5

%gometa

%global common_description %{expand:
Raft Autopilot.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Raft Autopilot

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/hashicorp/go-hclog)
BuildRequires:  golang(github.com/hashicorp/raft)
BuildRequires:  golang(golang.org/x/sync/semaphore)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/mock)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(go.uber.org/goleak)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

