# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/tencentcloud/tencentcloud-sdk-go
%global goipath         github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/kms
%global forgeurl        https://github.com/tencentcloud/tencentcloud-sdk-go
%global commit          41e03f14c6ede068bd9a13d13d2f57174eee440e

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.md README.md products.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

