# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/cloudfoundry/gosigar
%global goipath         github.com/cloudfoundry/gosigar
Version:                1.2.0

%gometa

%global common_description %{expand:
Total.}

%global golicenses      LICENSE NOTICE
%global godocs          examples README.md README-ci.md README-psnotify.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Total

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/onsi/ginkgo)
BuildRequires:  golang(github.com/onsi/gomega)
BuildRequires:  golang(github.com/onsi/gomega/gexec)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv ci/README.md README-ci.md
mv psnotify/README.md README-psnotify.md

%build
for cmd in fixtures/memory fixtures/stress; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE
%doc examples README.md README-ci.md README-psnotify.md
%{_bindir}/*

%gopkgfiles

%changelog

