# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/googleapis/google-api-go-client
%global goipath         google.golang.org/api
%global forgeurl        https://github.com/googleapis/google-api-go-client
Version:                0.10.0

%gometa

%global common_description %{expand:
Auto-generated Google APIs for Go.}

%global golicenses      LICENSE
%global godocs          docs examples CHANGES.md README.md GettingStarted.md\\\
                        CONTRIBUTORS TODO AUTHORS RELEASING.md\\\
                        CONTRIBUTING.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Auto-generated Google APIs for Go

# Upstream license specification: BSD-3-Clause and MIT
License:        BSD and MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/googleapis/gax-go/v2)
BuildRequires:  golang(go.opencensus.io/plugin/ocgrpc)
BuildRequires:  golang(go.opencensus.io/plugin/ochttp)
BuildRequires:  golang(go.opencensus.io/trace)
BuildRequires:  golang(go.opencensus.io/trace/propagation)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)
BuildRequires:  golang(golang.org/x/sync/semaphore)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(google.golang.org/genproto/googleapis/bytestream)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/balancer/grpclb)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/credentials/google)
BuildRequires:  golang(google.golang.org/grpc/credentials/oauth)
BuildRequires:  golang(google.golang.org/grpc/naming)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(google.golang.org/grpc/metadata)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in google-api-go-generator; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs examples CHANGES.md README.md GettingStarted.md CONTRIBUTORS TODO
%doc AUTHORS RELEASING.md CONTRIBUTING.md
%{_bindir}/*

%gopkgfiles

%changelog

