# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/tidwall/match
%global goipath         github.com/tidwall/match
Version:                1.0.3

%gometa

%global common_description %{expand:
Package match provides a simple pattern matcher with unicode support.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package match provides a simple pattern matcher with unicode support

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

