# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/docker/containerd
%global goipath         github.com/docker/containerd
Version:                0.2.8

%gometa

%global common_description %{expand:
See https://github.com/containerd/containerd for upstream containerd.}

%global golicenses      LICENSE.code LICENSE.docs NOTICE
%global godocs          docs CONTRIBUTING.md README.md example

Name:           %{goname}
Release:        1%{?dist}
Summary:        See https://github.com/containerd/containerd for upstream containerd

# Upstream license specification: Apache-2.0 and CC-BY-SA-4.0
License:        ASL 2.0 and CC-BY-SA-4.0
# FIXME: Upstream SPDX tag CC-BY-SA-4.0 not listed in Fedora's good licenses list.
# FIXME: This package might not be allowed in Fedora!

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cloudfoundry/gosigar)
BuildRequires:  golang(github.com/codegangsta/cli)
BuildRequires:  golang(github.com/cyberdelia/go-metrics-graphite)
BuildRequires:  golang(github.com/docker/docker/pkg/listeners)
BuildRequires:  golang(github.com/docker/docker/pkg/term)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/system)
BuildRequires:  golang(github.com/opencontainers/runtime-spec/specs-go)
BuildRequires:  golang(github.com/rcrowley/go-metrics)
BuildRequires:  golang(github.com/Sirupsen/logrus)
BuildRequires:  golang(github.com/tonistiigi/fifo)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/health)
BuildRequires:  golang(google.golang.org/grpc/health/grpc_health_v1)
BuildRequires:  golang(google.golang.org/grpc/transport)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in containerd containerd-shim ctr hack integration-test; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.code LICENSE.docs NOTICE
%doc docs CONTRIBUTING.md README.md example
%{_bindir}/*

%gopkgfiles

%changelog

