# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/segmentio/encoding
%global goipath         github.com/segmentio/encoding
Version:                0.2.19

%gometa

%global common_description %{expand:
Go package containing implementations of efficient encoding, decoding, and
validation APIs.}

%global golicenses      LICENSE LICENSE-json-fuzz
%global godocs          README.md easyjson+gzip-benchmarks-results.txt\\\
                        easyjson+snappy-benchmarks-results.txt\\\
                        easyjson+zstd-benchmarks-results.txt\\\
                        encoding-json+gzip-benchmarks-results.txt\\\
                        encoding-json+snappy-benchmarks-results.txt\\\
                        encoding-json+zstd-benchmarks-results.txt\\\
                        json-iterator+gzip-benchmarks-results.txt\\\
                        json-iterator+snappy-benchmarks-results.txt\\\
                        json-iterator+zstd-benchmarks-results.txt\\\
                        json-iterator-benchmarks-results.txt\\\
                        segment-encoding-json+gzip-benchmarks-results.txt\\\
                        segment-encoding-json+snappy-benchmarks-results.txt\\\
                        segment-encoding-json+zstd-benchmarks-results.txt\\\
                        segment-protobuf-v1+gzip-benchmarks-results.txt\\\
                        segment-protobuf-v1+snappy-benchmarks-results.txt\\\
                        segment-protobuf-v1+zstd-benchmarks-results.txt\\\
                        segment-protobuf-v1-benchmarks-results.txt\\\
                        tinylib-msgp+gzip-benchmarks-results.txt\\\
                        tinylib-msgp+snappy-benchmarks-results.txt\\\
                        tinylib-msgp+zstd-benchmarks-results.txt\\\
                        tinylib-msgp-benchmarks-results.txt\\\
                        vmihailenco-msgpack+gzip-benchmarks-results.txt\\\
                        vmihailenco-msgpack+snappy-benchmarks-results.txt\\\
                        vmihailenco-msgpack+zstd-benchmarks-results.txt\\\
                        vmihailenco-msgpack-benchmarks-results.txt\\\
                        README-json.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go package containing implementations of efficient encoding, decoding, and validation APIs

# Upstream license specification: Apache-2.0 and MIT
License:        ASL 2.0 and MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/klauspost/cpuid/v2)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)

%description
%{common_description}

%gopkg

%prep
%goprep
mv json/fuzz/LICENSE LICENSE-json-fuzz
mv benchmarks/results/easyjson+gzip.txt easyjson+gzip-benchmarks-results.txt
mv benchmarks/results/easyjson+snappy.txt easyjson+snappy-benchmarks-results.txt
mv benchmarks/results/easyjson+zstd.txt easyjson+zstd-benchmarks-results.txt
mv benchmarks/results/encoding-json+gzip.txt encoding-json+gzip-benchmarks-results.txt
mv benchmarks/results/encoding-json+snappy.txt encoding-json+snappy-benchmarks-results.txt
mv benchmarks/results/encoding-json+zstd.txt encoding-json+zstd-benchmarks-results.txt
mv benchmarks/results/json-iterator+gzip.txt json-iterator+gzip-benchmarks-results.txt
mv benchmarks/results/json-iterator+snappy.txt json-iterator+snappy-benchmarks-results.txt
mv benchmarks/results/json-iterator+zstd.txt json-iterator+zstd-benchmarks-results.txt
mv benchmarks/results/json-iterator.txt json-iterator-benchmarks-results.txt
mv benchmarks/results/segment-encoding-json+gzip.txt segment-encoding-json+gzip-benchmarks-results.txt
mv benchmarks/results/segment-encoding-json+snappy.txt segment-encoding-json+snappy-benchmarks-results.txt
mv benchmarks/results/segment-encoding-json+zstd.txt segment-encoding-json+zstd-benchmarks-results.txt
mv benchmarks/results/segment-protobuf-v1+gzip.txt segment-protobuf-v1+gzip-benchmarks-results.txt
mv benchmarks/results/segment-protobuf-v1+snappy.txt segment-protobuf-v1+snappy-benchmarks-results.txt
mv benchmarks/results/segment-protobuf-v1+zstd.txt segment-protobuf-v1+zstd-benchmarks-results.txt
mv benchmarks/results/segment-protobuf-v1.txt segment-protobuf-v1-benchmarks-results.txt
mv benchmarks/results/tinylib-msgp+gzip.txt tinylib-msgp+gzip-benchmarks-results.txt
mv benchmarks/results/tinylib-msgp+snappy.txt tinylib-msgp+snappy-benchmarks-results.txt
mv benchmarks/results/tinylib-msgp+zstd.txt tinylib-msgp+zstd-benchmarks-results.txt
mv benchmarks/results/tinylib-msgp.txt tinylib-msgp-benchmarks-results.txt
mv benchmarks/results/vmihailenco-msgpack+gzip.txt vmihailenco-msgpack+gzip-benchmarks-results.txt
mv benchmarks/results/vmihailenco-msgpack+snappy.txt vmihailenco-msgpack+snappy-benchmarks-results.txt
mv benchmarks/results/vmihailenco-msgpack+zstd.txt vmihailenco-msgpack+zstd-benchmarks-results.txt
mv benchmarks/results/vmihailenco-msgpack.txt vmihailenco-msgpack-benchmarks-results.txt
mv json/README.md README-json.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-json-fuzz
%doc README.md easyjson+gzip-benchmarks-results.txt
%doc easyjson+snappy-benchmarks-results.txt easyjson+zstd-benchmarks-results.txt
%doc encoding-json+gzip-benchmarks-results.txt
%doc encoding-json+snappy-benchmarks-results.txt
%doc encoding-json+zstd-benchmarks-results.txt
%doc json-iterator+gzip-benchmarks-results.txt
%doc json-iterator+snappy-benchmarks-results.txt
%doc json-iterator+zstd-benchmarks-results.txt
%doc json-iterator-benchmarks-results.txt
%doc segment-encoding-json+gzip-benchmarks-results.txt
%doc segment-encoding-json+snappy-benchmarks-results.txt
%doc segment-encoding-json+zstd-benchmarks-results.txt
%doc segment-protobuf-v1+gzip-benchmarks-results.txt
%doc segment-protobuf-v1+snappy-benchmarks-results.txt
%doc segment-protobuf-v1+zstd-benchmarks-results.txt
%doc segment-protobuf-v1-benchmarks-results.txt
%doc tinylib-msgp+gzip-benchmarks-results.txt
%doc tinylib-msgp+snappy-benchmarks-results.txt
%doc tinylib-msgp+zstd-benchmarks-results.txt
%doc tinylib-msgp-benchmarks-results.txt
%doc vmihailenco-msgpack+gzip-benchmarks-results.txt
%doc vmihailenco-msgpack+snappy-benchmarks-results.txt
%doc vmihailenco-msgpack+zstd-benchmarks-results.txt
%doc vmihailenco-msgpack-benchmarks-results.txt README-json.md

%gopkgfiles

%changelog

