# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/klauspost/cpuid
%global goipath         github.com/klauspost/cpuid/v2
%global forgeurl        https://github.com/klauspost/cpuid
Version:                2.0.6

%gometa

%global common_description %{expand:
CPU feature identification for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.txt README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        CPU feature identification for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.txt README.md

%gopkgfiles

%changelog

