# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/airbrake/gobrake
%global goipath         gopkg.in/airbrake/gobrake.v2
%global forgeurl        https://github.com/airbrake/gobrake
Version:                2.0.9

%gometa

%global common_description %{expand:
Airbrake notifier for Golang.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Airbrake notifier for Golang

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

