# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/goreleaser/chglog
%global goipath         github.com/goreleaser/chglog
Version:                0.1.2

%gometa

%global common_description %{expand:
Chglog is a changelog management library and tool.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Chglog is a changelog management library and tool

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-git/go-git/v5)
BuildRequires:  golang(github.com/go-git/go-git/v5/plumbing)
BuildRequires:  golang(github.com/go-git/go-git/v5/plumbing/object)
BuildRequires:  golang(github.com/go-git/go-git/v5/plumbing/storer)
BuildRequires:  golang(github.com/Masterminds/semver)
BuildRequires:  golang(github.com/Masterminds/semver/v3)
BuildRequires:  golang(github.com/Masterminds/sprig)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog

