# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/campoy/unique
%global goipath         github.com/campoy/unique
%global commit          88950e537e7e644cd746a3102037b5d2b723e9f5

%gometa

%global common_description %{expand:
Package unique provides primitives for sorting slices removing repeated
elements.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Package unique provides primitives for sorting slices removing repeated elements

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

