# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/stevvooe/resumable
%global goipath         github.com/stevvooe/resumable
%global commit          22b14a53ba50b6c0c575a314a13ef21142f0b466

%gometa

%global common_description %{expand:
A Subset of the Go `crypto` Package with a Resumable Hash Interface.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Subset of the Go `crypto` Package with a Resumable Hash Interface

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

