# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/go-raftchunking
%global goipath         github.com/hashicorp/go-raftchunking
Version:                0.6.2

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/raft)
BuildRequires:  golang(github.com/mitchellh/copystructure)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/go-test/deep)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

