# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/bitly/go-hostpool
%global goipath         github.com/bitly/go-hostpool
Version:                0.1.0

%gometa

%global common_description %{expand:
Intelligently and flexibly pool among multiple hosts from your Go application.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Intelligently and flexibly pool among multiple hosts from your Go application

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

