# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/beego/goyaml2
%global goipath         github.com/beego/goyaml2
Version:                2.0
%global tag             2.0

%gometa

%global common_description %{expand:
YAML for Golang.}

%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        YAML for Golang

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/wendal/errors)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

