# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/aarzilli/sandblast
%global goipath         github.com/aarzilli/sandblast
%global commit          43f8fb998d06140736b7a019d227bdda434d9487

%gometa

%global common_description %{expand:
Library to extract text from HTML files.}

%global golicenses      COPYING
%global godocs          example README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Library to extract text from HTML files

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/net/html)
BuildRequires:  golang(golang.org/x/net/html/charset)
BuildRequires:  golang(golang.org/x/text/transform)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in qa; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING
%doc example README.md
%{_bindir}/*

%gopkgfiles

%changelog

