# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/aws-sdk-go
%global goipath         github.com/hashicorp/aws-sdk-go
Version:                tf0.4.0
%global tag             tf0.4.0
%global commit          1d5c8f6b881ab3e2e0c3e737886732bbfd1ced27

%gometa

%global common_description %{expand:
A fork of awslabs/aws-sdk-go to keep hashicorp/terraform stable. You should use
awslabs/aws-sdk-go instead.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A fork of awslabs/aws-sdk-go to keep hashicorp/terraform stable. You should use awslabs/aws-sdk-go instead

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aarzilli/sandblast)
BuildRequires:  golang(github.com/vaughan0/go-ini)
BuildRequires:  golang(golang.org/x/net/html)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog

