# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/goreleaser/goreleaser
%global goipath         github.com/goreleaser/goreleaser
Version:                0.169.0

%gometa

%global common_description %{expand:
Deliver Go binaries as fast and easily as possible.}

%global golicenses      LICENSE.md
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md docs

Name:           %{goname}
Release:        1%{?dist}
Summary:        Deliver Go binaries as fast and easily as possible

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(code.gitea.io/sdk/gitea)
BuildRequires:  golang(github.com/apex/log)
BuildRequires:  golang(github.com/apex/log/handlers/cli)
BuildRequires:  golang(github.com/caarlos0/ctrlc)
BuildRequires:  golang(github.com/caarlos0/env/v6)
BuildRequires:  golang(github.com/caarlos0/go-shellwords)
BuildRequires:  golang(github.com/campoy/unique)
BuildRequires:  golang(github.com/dghubble/go-twitter/twitter)
BuildRequires:  golang(github.com/dghubble/oauth1)
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/google/go-github/v35/github)
BuildRequires:  golang(github.com/goreleaser/fileglob)
BuildRequires:  golang(github.com/goreleaser/nfpm/v2)
BuildRequires:  golang(github.com/goreleaser/nfpm/v2/apk)
BuildRequires:  golang(github.com/goreleaser/nfpm/v2/deb)
BuildRequires:  golang(github.com/goreleaser/nfpm/v2/files)
BuildRequires:  golang(github.com/goreleaser/nfpm/v2/rpm)
BuildRequires:  golang(github.com/imdario/mergo)
BuildRequires:  golang(github.com/Masterminds/semver/v3)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/cobra/doc)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(github.com/ulikunitz/xz)
BuildRequires:  golang(github.com/xanzy/go-gitlab)
BuildRequires:  golang(gocloud.dev/blob)
BuildRequires:  golang(gocloud.dev/blob/azureblob)
BuildRequires:  golang(gocloud.dev/blob/gcsblob)
BuildRequires:  golang(gocloud.dev/blob/s3blob)
BuildRequires:  golang(gocloud.dev/secrets)
BuildRequires:  golang(gocloud.dev/secrets/awskms)
BuildRequires:  golang(gocloud.dev/secrets/azurekeyvault)
BuildRequires:  golang(gocloud.dev/secrets/gcpkms)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/jarcoal/httpmock)
BuildRequires:  golang(github.com/stretchr/testify/suite)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/goreleaser %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md docs
%{_bindir}/*

%gopkgfiles

%changelog

