# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/go-ldap/ldap
%global goipath         github.com/go-ldap/ldap
Version:                3.0.3

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(gopkg.in/asn1-ber.v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck -r .*ldap.*
%endif

%gopkgfiles

%changelog

