# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/labstack/echo
%global goipath         github.com/labstack/echo
Version:                3.3.10

%gometa

%global common_description %{expand:
High performance, minimalist Go web framework.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        High performance, minimalist Go web framework

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/dgrijalva/jwt-go)
BuildRequires:  golang(github.com/labstack/gommon/bytes)
BuildRequires:  golang(github.com/labstack/gommon/color)
BuildRequires:  golang(github.com/labstack/gommon/log)
BuildRequires:  golang(github.com/labstack/gommon/random)
BuildRequires:  golang(github.com/valyala/fasttemplate)
BuildRequires:  golang(golang.org/x/crypto/acme/autocert)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

