# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/xanzy/go-gitlab
%global goipath         github.com/xanzy/go-gitlab
Version:                0.50.0

%gometa

%global common_description %{expand:
A GitLab API client enabling Go programs to interact with GitLab in a simple
and uniform way.}

%global golicenses      LICENSE license.go license_templates.go
%global godocs          examples README.md todos.go todos_test.go

Name:           %{goname}
Release:        1%{?dist}
Summary:        A GitLab API client enabling Go programs to interact with GitLab in a simple and uniform way

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/google/go-querystring/query)
BuildRequires:  golang(github.com/hashicorp/go-cleanhttp)
BuildRequires:  golang(github.com/hashicorp/go-retryablehttp)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/time/rate)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

