# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/distribution/distribution
%global goipath         github.com/distribution/distribution/v3
Version:                2.7.1

%gometa

%global common_description %{expand:
The toolkit to pack, ship, store, and deliver container content.}

%global golicenses      LICENSE
%global godocs          docs BUILDING.md CONTRIBUTING.md README.md ROADMAP.md\\\
                        contrib/apache/README.MD contrib/compose/README.md\\\
                        contrib/docker-integration/README.md\\\
                        project/hooks/README.md releases/v2.5.0-changelog.txt\\\
                        releases/v2.6.0-changelog.txt releases/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The toolkit to pack, ship, store, and deliver container content

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/corehandlers)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/endpoints)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/cloudfront/sign)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/storage)
BuildRequires:  golang(github.com/bshuster-repo/logrus-logstash-hook)
BuildRequires:  golang(github.com/bugsnag/bugsnag-go)
BuildRequires:  golang(github.com/docker/distribution)
BuildRequires:  golang(github.com/docker/distribution/configuration)
BuildRequires:  golang(github.com/docker/distribution/context)
BuildRequires:  golang(github.com/docker/distribution/digestset)
BuildRequires:  golang(github.com/docker/distribution/health)
BuildRequires:  golang(github.com/docker/distribution/health/checks)
BuildRequires:  golang(github.com/docker/distribution/manifest)
BuildRequires:  golang(github.com/docker/distribution/manifest/manifestlist)
BuildRequires:  golang(github.com/docker/distribution/manifest/ocischema)
BuildRequires:  golang(github.com/docker/distribution/manifest/schema1)
BuildRequires:  golang(github.com/docker/distribution/manifest/schema2)
BuildRequires:  golang(github.com/docker/distribution/metrics)
BuildRequires:  golang(github.com/docker/distribution/notifications)
BuildRequires:  golang(github.com/docker/distribution/reference)
BuildRequires:  golang(github.com/docker/distribution/registry)
BuildRequires:  golang(github.com/docker/distribution/registry/api/errcode)
BuildRequires:  golang(github.com/docker/distribution/registry/api/v2)
BuildRequires:  golang(github.com/docker/distribution/registry/auth)
BuildRequires:  golang(github.com/docker/distribution/registry/auth/htpasswd)
BuildRequires:  golang(github.com/docker/distribution/registry/auth/silly)
BuildRequires:  golang(github.com/docker/distribution/registry/auth/token)
BuildRequires:  golang(github.com/docker/distribution/registry/client)
BuildRequires:  golang(github.com/docker/distribution/registry/client/auth)
BuildRequires:  golang(github.com/docker/distribution/registry/client/auth/challenge)
BuildRequires:  golang(github.com/docker/distribution/registry/client/transport)
BuildRequires:  golang(github.com/docker/distribution/registry/handlers)
BuildRequires:  golang(github.com/docker/distribution/registry/listener)
BuildRequires:  golang(github.com/docker/distribution/registry/middleware/registry)
BuildRequires:  golang(github.com/docker/distribution/registry/middleware/repository)
BuildRequires:  golang(github.com/docker/distribution/registry/proxy)
BuildRequires:  golang(github.com/docker/distribution/registry/proxy/scheduler)
BuildRequires:  golang(github.com/docker/distribution/registry/storage)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/cache)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/cache/memory)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/cache/redis)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/azure)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/base)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/factory)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/filesystem)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/gcs)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/inmemory)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/middleware)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/middleware/cloudfront)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/middleware/redirect)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/oss)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/s3-aws)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/swift)
BuildRequires:  golang(github.com/docker/distribution/uuid)
BuildRequires:  golang(github.com/docker/distribution/version)
BuildRequires:  golang(github.com/docker/go-metrics)
BuildRequires:  golang(github.com/docker/libtrust)
BuildRequires:  golang(github.com/garyburd/redigo/redis)
BuildRequires:  golang(github.com/gorilla/handlers)
BuildRequires:  golang(github.com/gorilla/mux)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/ncw/swift)
BuildRequires:  golang(github.com/opencontainers/go-digest)
BuildRequires:  golang(github.com/opencontainers/image-spec/specs-go/v1)
BuildRequires:  golang(github.com/Shopify/logrus-bugsnag)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/yvasiyarov/gorelic)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(gopkg.in/check.v1)
BuildRequires:  golang(gopkg.in/yaml.v2)
BuildRequires:  golang(rsc.io/letsencrypt)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/docker/distribution/registry/storage/cache/cachecheck)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/testdriver)
BuildRequires:  golang(github.com/docker/distribution/registry/storage/driver/testsuites)
BuildRequires:  golang(github.com/docker/distribution/testutil)
BuildRequires:  golang(github.com/ncw/swift/swifttest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in contrib/token-server; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs BUILDING.md CONTRIBUTING.md README.md ROADMAP.md
%doc contrib/apache/README.MD contrib/compose/README.md
%doc contrib/docker-integration/README.md project/hooks/README.md
%doc releases/v2.5.0-changelog.txt releases/v2.6.0-changelog.txt
%doc releases/README.md
%{_bindir}/*

%gopkgfiles

%changelog

