# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/docker/docker
%global goipath         github.com/docker/docker
Version:                1.12.6

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE NOTICE contrib/syntax/vim/LICENSE\\\
                        contrib/selinux-fedora-24/docker-engine-\\\
                        selinux/LICENSE contrib/selinux-oraclelinux-7/docker-\\\
                        engine-selinux/LICENSE contrib/selinux/docker-engine-\\\
                        selinux/LICENSE pkg/mflag/LICENSE\\\
                        pkg/symlink/LICENSE.APACHE pkg/symlink/LICENSE.BSD
%global godocs          docs AUTHORS CHANGELOG.md CONTRIBUTING.md README.md\\\
                        ROADMAP.md VENDORING.md api/README.md\\\
                        cmd/dockerd/README.md contrib/README.md\\\
                        contrib/docker-device-tool/README.md\\\
                        contrib/syntax/nano/README.md\\\
                        contrib/syntax/textmate/README.md doc\\\
                        contrib/syntax/vim/README.md\\\
                        contrib/builder/deb/amd64/README.md\\\
                        contrib/builder/rpm/amd64/README.md contrib/desktop-\\\
                        integration/README.md contrib/selinux-\\\
                        fedora-24/docker-engine-selinux/README.md\\\
                        contrib/selinux-oraclelinux-7/docker-engine-\\\
                        selinux/README.md contrib/vagrant-docker/README.md\\\
                        daemon/graphdriver/devmapper/README.md\\\
                        hack/make/README.md hack/Jenkins/readme.md\\\
                        image/spec/v1.1.md image/spec/v1.2.md\\\
                        image/spec/v1.md pkg/README.md pkg/archive/README.md\\\
                        pkg/discovery/README.md pkg/locker/README.md\\\
                        pkg/plugins/pluginrpc-gen/README.md\\\
                        pkg/reexec/README.md pkg/signal/README.md\\\
                        pkg/stringid/README.md pkg/sysinfo/README.md\\\
                        pkg/tarsum/tarsum_spec.md pkg/useragent/README.md\\\
                        example pkg/mflag/README.md pkg/stringutils/README.md\\\
                        pkg/symlink/README.md project/BRANCHES-AND-TAGS.md\\\
                        project/PATCH-RELEASES.md project/PRINCIPLES.md\\\
                        project/ARM.md project/CONTRIBUTORS.md\\\
                        project/GOVERNANCE.md project/IRC-ADMINISTRATION.md\\\
                        project/ISSUE-TRIAGE.md project/PACKAGE-REPO-\\\
                        MAINTENANCE.md project/PACKAGERS.md project/README.md\\\
                        project/RELEASE-CHECKLIST.md project/RELEASE-\\\
                        PROCESS.md project/REVIEWING.md project/TOOLS.md\\\
                        experimental/README.md experimental/docker-stacks-\\\
                        and-bundles.md experimental/plugins_graphdriver.md\\\
                        experimental/vlan-networks.md man/Dockerfile.5.md\\\
                        man/README.md man/docker-attach.1.md man/docker-\\\
                        build.1.md man/docker-commit.1.md man/docker-config-\\\
                        json.5.md man/docker-cp.1.md man/docker-create.1.md\\\
                        man/docker-diff.1.md man/docker-events.1.md\\\
                        man/docker-exec.1.md man/docker-export.1.md\\\
                        man/docker-history.1.md man/docker-images.1.md\\\
                        man/docker-import.1.md man/docker-info.1.md\\\
                        man/docker-inspect.1.md man/docker-kill.1.md\\\
                        man/docker-load.1.md man/docker-login.1.md\\\
                        man/docker-logout.1.md man/docker-logs.1.md\\\
                        man/docker-network-connect.1.md man/docker-network-\\\
                        create.1.md man/docker-network-disconnect.1.md\\\
                        man/docker-network-inspect.1.md man/docker-network-\\\
                        ls.1.md man/docker-network-rm.1.md man/docker-\\\
                        pause.1.md man/docker-port.1.md man/docker-ps.1.md\\\
                        man/docker-pull.1.md man/docker-push.1.md man/docker-\\\
                        rename.1.md man/docker-restart.1.md man/docker-\\\
                        rm.1.md man/docker-rmi.1.md man/docker-run.1.md\\\
                        man/docker-save.1.md man/docker-search.1.md\\\
                        man/docker-start.1.md man/docker-stats.1.md\\\
                        man/docker-stop.1.md man/docker-tag.1.md man/docker-\\\
                        top.1.md man/docker-unpause.1.md man/docker-\\\
                        update.1.md man/docker-version.1.md man/docker-\\\
                        wait.1.md man/docker.1.md man/dockerd.8.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0 and BSD-2-Clause and BSD-3-Clause and GPL-2.0-only
License:        ASL 2.0 and BSD and GPL-2.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-2.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/cloudwatchlogs)
BuildRequires:  golang(github.com/Azure/go-ansiterm)
BuildRequires:  golang(github.com/boltdb/bolt)
BuildRequires:  golang(github.com/coreos/go-systemd/activation)
BuildRequires:  golang(github.com/coreos/go-systemd/daemon)
BuildRequires:  golang(github.com/coreos/go-systemd/journal)
BuildRequires:  golang(github.com/docker/containerd/api/grpc/types)
BuildRequires:  golang(github.com/docker/distribution)
BuildRequires:  golang(github.com/docker/distribution/context)
BuildRequires:  golang(github.com/docker/distribution/digest)
BuildRequires:  golang(github.com/docker/distribution/manifest/manifestlist)
BuildRequires:  golang(github.com/docker/distribution/manifest/schema1)
BuildRequires:  golang(github.com/docker/distribution/manifest/schema2)
BuildRequires:  golang(github.com/docker/distribution/reference)
BuildRequires:  golang(github.com/docker/distribution/registry/api/errcode)
BuildRequires:  golang(github.com/docker/distribution/registry/api/v2)
BuildRequires:  golang(github.com/docker/distribution/registry/client)
BuildRequires:  golang(github.com/docker/distribution/registry/client/auth)
BuildRequires:  golang(github.com/docker/distribution/registry/client/transport)
BuildRequires:  golang(github.com/docker/distribution/uuid)
BuildRequires:  golang(github.com/docker/engine-api/client)
BuildRequires:  golang(github.com/docker/engine-api/types)
BuildRequires:  golang(github.com/docker/engine-api/types/blkiodev)
BuildRequires:  golang(github.com/docker/engine-api/types/container)
BuildRequires:  golang(github.com/docker/engine-api/types/events)
BuildRequires:  golang(github.com/docker/engine-api/types/filters)
BuildRequires:  golang(github.com/docker/engine-api/types/network)
BuildRequires:  golang(github.com/docker/engine-api/types/registry)
BuildRequires:  golang(github.com/docker/engine-api/types/strslice)
BuildRequires:  golang(github.com/docker/engine-api/types/swarm)
BuildRequires:  golang(github.com/docker/engine-api/types/time)
BuildRequires:  golang(github.com/docker/engine-api/types/versions)
BuildRequires:  golang(github.com/docker/engine-api/types/versions/v1p19)
BuildRequires:  golang(github.com/docker/engine-api/types/versions/v1p20)
BuildRequires:  golang(github.com/docker/go-connections/nat)
BuildRequires:  golang(github.com/docker/go-connections/sockets)
BuildRequires:  golang(github.com/docker/go-connections/tlsconfig)
BuildRequires:  golang(github.com/docker/go-units)
BuildRequires:  golang(github.com/docker/libkv)
BuildRequires:  golang(github.com/docker/libkv/store)
BuildRequires:  golang(github.com/docker/libkv/store/consul)
BuildRequires:  golang(github.com/docker/libkv/store/etcd)
BuildRequires:  golang(github.com/docker/libkv/store/zookeeper)
BuildRequires:  golang(github.com/docker/libnetwork)
BuildRequires:  golang(github.com/docker/libnetwork/cluster)
BuildRequires:  golang(github.com/docker/libnetwork/config)
BuildRequires:  golang(github.com/docker/libnetwork/drivers/bridge)
BuildRequires:  golang(github.com/docker/libnetwork/netlabel)
BuildRequires:  golang(github.com/docker/libnetwork/netutils)
BuildRequires:  golang(github.com/docker/libnetwork/options)
BuildRequires:  golang(github.com/docker/libnetwork/portallocator)
BuildRequires:  golang(github.com/docker/libnetwork/resolvconf/dns)
BuildRequires:  golang(github.com/docker/libnetwork/types)
BuildRequires:  golang(github.com/docker/libtrust)
BuildRequires:  golang(github.com/docker/notary/client)
BuildRequires:  golang(github.com/docker/notary/passphrase)
BuildRequires:  golang(github.com/docker/notary/trustmanager)
BuildRequires:  golang(github.com/docker/notary/trustpinning)
BuildRequires:  golang(github.com/docker/notary/tuf/data)
BuildRequires:  golang(github.com/docker/notary/tuf/signed)
BuildRequires:  golang(github.com/docker/notary/tuf/store)
BuildRequires:  golang(github.com/docker/swarmkit/agent)
BuildRequires:  golang(github.com/docker/swarmkit/agent/exec)
BuildRequires:  golang(github.com/docker/swarmkit/api)
BuildRequires:  golang(github.com/docker/swarmkit/log)
BuildRequires:  golang(github.com/docker/swarmkit/protobuf/ptypes)
BuildRequires:  golang(github.com/fluent/fluent-logger-golang/fluent)
BuildRequires:  golang(github.com/flynn-archive/go-shlex)
BuildRequires:  golang(github.com/go-check/check)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/gorilla/mux)
BuildRequires:  golang(github.com/Graylog2/go-gelf/gelf)
BuildRequires:  golang(github.com/imdario/mergo)
BuildRequires:  golang(github.com/mattn/go-shellwords)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(github.com/mistifyio/go-zfs)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/apparmor)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/cgroups)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/configs)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/devices)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/label)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/selinux)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/system)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/user)
BuildRequires:  golang(github.com/opencontainers/specs/specs-go)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/RackSec/srslog)
BuildRequires:  golang(github.com/Sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/spf13/cobra/doc)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/syndtr/gocapability/capability)
BuildRequires:  golang(github.com/tchap/go-patricia/patricia)
BuildRequires:  golang(github.com/tonistiigi/fifo)
BuildRequires:  golang(github.com/vbatts/tar-split/tar/asm)
BuildRequires:  golang(github.com/vbatts/tar-split/tar/storage)
BuildRequires:  golang(github.com/vdemeester/shakers)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/net/websocket)
BuildRequires:  golang(google.golang.org/cloud/compute/metadata)
BuildRequires:  golang(google.golang.org/cloud/logging)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/transport)
BuildRequires:  golang(gopkg.in/fsnotify.v1)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/docker/distribution/manifest)
BuildRequires:  golang(github.com/docker/libnetwork/driverapi)
BuildRequires:  golang(github.com/docker/libnetwork/drivers/remote/api)
BuildRequires:  golang(github.com/docker/libnetwork/ipamapi)
BuildRequires:  golang(github.com/docker/libnetwork/ipams/remote/api)
BuildRequires:  golang(github.com/docker/libnetwork/iptables)
BuildRequires:  golang(github.com/docker/libnetwork/resolvconf)
BuildRequires:  golang(github.com/kr/pty)
BuildRequires:  golang(github.com/vishvananda/netlink)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in builder/dockerfile/parser/dumper contrib/apparmor contrib/docker-device-tool contrib/httpserver integration-cli man pkg/archive pkg/plugins/pluginrpc-gen profiles/seccomp; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE NOTICE contrib/syntax/vim/LICENSE
%license contrib/selinux-fedora-24/docker-engine-selinux/LICENSE
%license contrib/selinux-oraclelinux-7/docker-engine-selinux/LICENSE
%license contrib/selinux/docker-engine-selinux/LICENSE pkg/mflag/LICENSE
%license pkg/symlink/LICENSE.APACHE pkg/symlink/LICENSE.BSD
%doc docs AUTHORS CHANGELOG.md CONTRIBUTING.md README.md ROADMAP.md VENDORING.md
%doc api/README.md cmd/dockerd/README.md contrib/README.md
%doc contrib/docker-device-tool/README.md contrib/syntax/nano/README.md
%doc contrib/syntax/textmate/README.md doc contrib/syntax/vim/README.md
%doc contrib/builder/deb/amd64/README.md contrib/builder/rpm/amd64/README.md
%doc contrib/desktop-integration/README.md
%doc contrib/selinux-fedora-24/docker-engine-selinux/README.md
%doc contrib/selinux-oraclelinux-7/docker-engine-selinux/README.md
%doc contrib/vagrant-docker/README.md daemon/graphdriver/devmapper/README.md
%doc hack/make/README.md hack/Jenkins/readme.md image/spec/v1.1.md
%doc image/spec/v1.2.md image/spec/v1.md pkg/README.md pkg/archive/README.md
%doc pkg/discovery/README.md pkg/locker/README.md
%doc pkg/plugins/pluginrpc-gen/README.md pkg/reexec/README.md
%doc pkg/signal/README.md pkg/stringid/README.md pkg/sysinfo/README.md
%doc pkg/tarsum/tarsum_spec.md pkg/useragent/README.md example
%doc pkg/mflag/README.md pkg/stringutils/README.md pkg/symlink/README.md
%doc project/BRANCHES-AND-TAGS.md project/PATCH-RELEASES.md
%doc project/PRINCIPLES.md project/ARM.md project/CONTRIBUTORS.md
%doc project/GOVERNANCE.md project/IRC-ADMINISTRATION.md project/ISSUE-TRIAGE.md
%doc project/PACKAGE-REPO-MAINTENANCE.md project/PACKAGERS.md project/README.md
%doc project/RELEASE-CHECKLIST.md project/RELEASE-PROCESS.md
%doc project/REVIEWING.md project/TOOLS.md experimental/README.md
%doc experimental/docker-stacks-and-bundles.md
%doc experimental/plugins_graphdriver.md experimental/vlan-networks.md
%doc man/Dockerfile.5.md man/README.md man/docker-attach.1.md
%doc man/docker-build.1.md man/docker-commit.1.md man/docker-config-json.5.md
%doc man/docker-cp.1.md man/docker-create.1.md man/docker-diff.1.md
%doc man/docker-events.1.md man/docker-exec.1.md man/docker-export.1.md
%doc man/docker-history.1.md man/docker-images.1.md man/docker-import.1.md
%doc man/docker-info.1.md man/docker-inspect.1.md man/docker-kill.1.md
%doc man/docker-load.1.md man/docker-login.1.md man/docker-logout.1.md
%doc man/docker-logs.1.md man/docker-network-connect.1.md
%doc man/docker-network-create.1.md man/docker-network-disconnect.1.md
%doc man/docker-network-inspect.1.md man/docker-network-ls.1.md
%doc man/docker-network-rm.1.md man/docker-pause.1.md man/docker-port.1.md
%doc man/docker-ps.1.md man/docker-pull.1.md man/docker-push.1.md
%doc man/docker-rename.1.md man/docker-restart.1.md man/docker-rm.1.md
%doc man/docker-rmi.1.md man/docker-run.1.md man/docker-save.1.md
%doc man/docker-search.1.md man/docker-start.1.md man/docker-stats.1.md
%doc man/docker-stop.1.md man/docker-tag.1.md man/docker-top.1.md
%doc man/docker-unpause.1.md man/docker-update.1.md man/docker-version.1.md
%doc man/docker-wait.1.md man/docker.1.md man/dockerd.8.md
%{_bindir}/*

%gopkgfiles

%changelog

