# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/tj/go-spin
%global goipath         github.com/tj/go-spin
Version:                1.1.0

%gometa

%global common_description %{expand:
Terminal spinner package for Golang.}

%global godocs          example Readme.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Terminal spinner package for Golang

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

