# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/stretchr/testify
%global goipath         github.com/stretchr/testify
Version:                1.7.0

%gometa

%global common_description %{expand:
A toolkit with common assertions and mocks that plays nicely with the standard
library.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md MAINTAINERS.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A toolkit with common assertions and mocks that plays nicely with the standard library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/davecgh/go-spew/spew)
BuildRequires:  golang(github.com/pmezard/go-difflib/difflib)
BuildRequires:  golang(github.com/stretchr/objx)
BuildRequires:  golang(gopkg.in/yaml.v3)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md MAINTAINERS.md README.md

%gopkgfiles

%changelog

