# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/LK4D4/joincontext
%global goipath         github.com/LK4D4/joincontext
%global commit          1724345da6d5bcc8b66fefb843b607ab918e175c

%gometa

%global common_description %{expand:
Package joincontext provides a way to combine two contexts. For example it
might be useful for grpc server to cancel all handlers in addition to provided
handler context.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Package joincontext provides a way to combine two contexts

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/net/context)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

