# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/aws-sdk-go
%global goipath         github.com/hashicorp/aws-sdk-go
Version:                tf0.4.0
%global tag             tf0.4.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aarzilli/sandblast)
BuildRequires:  golang(github.com/vaughan0/go-ini)
BuildRequires:  golang(golang.org/x/net/html)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md

%gopkgfiles

%changelog

