# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/vault
%global goipath         github.com/hashicorp/vault/sdk
Version:                0.2.0

%gometa

%global common_description %{expand:
A tool for secrets management, encryption as a service, and privileged access
management.}

%global golicenses      LICENSE website/LICENSE.md
%global godocs          CHANGELOG.md README.md api/SPEC.md website/README.md\\\
                        website/version.txt docs website/source/robots.txt\\\
                        examples website/source/intro/use-cases.html.markdown\\\
                        website/source/intro/index.html.markdown\\\
                        website/source/intro/getting-started/acl.html.md\\\
                        website/source/intro/getting-\\\
                        started/authentication.html.md\\\
                        website/source/intro/getting-started/deploy.html.md\\\
                        website/source/intro/getting-started/dev-\\\
                        server.html.md website/source/intro/getting-\\\
                        started/dynamic-secrets.html.md\\\
                        website/source/intro/getting-started/first-\\\
                        secret.html.md website/source/intro/getting-\\\
                        started/help.html.md website/source/intro/getting-\\\
                        started/install.html.md website/source/intro/getting-\\\
                        started/next-steps.html.md\\\
                        website/source/intro/getting-started/secret-\\\
                        backends.html.md\\\
                        website/source/intro/vs/dropbox.html.md\\\
                        website/source/intro/vs/index.html.markdown\\\
                        website/source/intro/vs/chef-puppet-etc.html.md\\\
                        website/source/intro/vs/consul.html.md\\\
                        website/source/intro/vs/custom.html.markdown\\\
                        website/source/intro/vs/hsm.html.md\\\
                        website/source/intro/vs/keywhiz.html.md\\\
                        website/source/intro/vs/kms.html.md\\\
                        terraform/aws/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A tool for secrets management, encryption as a service, and privileged access management

# Upstream license specification: BSD-3-Clause and MIT and MPL-2.0
License:        BSD and MIT and MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/armon/go-metrics)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/coreos/go-etcd/etcd)
BuildRequires:  golang(github.com/fatih/structs)
BuildRequires:  golang(github.com/go-ldap/ldap)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/gocql/gocql)
BuildRequires:  golang(github.com/google/go-github/github)
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/aws)
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/gen/iam)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-syslog)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/hashicorp/hcl)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl)
BuildRequires:  golang(github.com/hashicorp/logutils)
BuildRequires:  golang(github.com/kardianos/osext)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/copystructure)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/ryanuber/columnize)
BuildRequires:  golang(github.com/samuel/go-zookeeper/zk)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)
BuildRequires:  golang(golang.org/x/oauth2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/hashicorp/aws-sdk-go/gen/ec2)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/sdk %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE website/LICENSE.md
%doc CHANGELOG.md README.md api/SPEC.md website/README.md website/version.txt
%doc docs website/source/robots.txt examples
%doc website/source/intro/use-cases.html.markdown
%doc website/source/intro/index.html.markdown
%doc website/source/intro/getting-started/acl.html.md
%doc website/source/intro/getting-started/authentication.html.md
%doc website/source/intro/getting-started/deploy.html.md
%doc website/source/intro/getting-started/dev-server.html.md
%doc website/source/intro/getting-started/dynamic-secrets.html.md
%doc website/source/intro/getting-started/first-secret.html.md
%doc website/source/intro/getting-started/help.html.md
%doc website/source/intro/getting-started/install.html.md
%doc website/source/intro/getting-started/next-steps.html.md
%doc website/source/intro/getting-started/secret-backends.html.md
%doc website/source/intro/vs/dropbox.html.md
%doc website/source/intro/vs/index.html.markdown
%doc website/source/intro/vs/chef-puppet-etc.html.md
%doc website/source/intro/vs/consul.html.md
%doc website/source/intro/vs/custom.html.markdown
%doc website/source/intro/vs/hsm.html.md website/source/intro/vs/keywhiz.html.md
%doc website/source/intro/vs/kms.html.md terraform/aws/README.md
%{_bindir}/*

%gopkgfiles

%changelog

