# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/openlyinc/pointy
%global goipath         github.com/openlyinc/pointy
Version:                1.1.2

%gometa

%global common_description %{expand:
Package pointy is a set of simple helper functions to provide a shorthand to
get a pointer to a variable holding a constant.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package pointy is a set of simple helper functions to provide a shorthand to get a pointer to a variable holding a constant

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

