# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/ory-am/dockertest
%global goipath         gopkg.in/ory-am/dockertest.v2
%global forgeurl        https://github.com/ory-am/dockertest
Version:                2.2.3

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-errors/errors)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/ory-am/common/env)
BuildRequires:  golang(github.com/pborman/uuid)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/coreos/etcd/clientv3)
BuildRequires:  golang(github.com/dancannon/gorethink)
BuildRequires:  golang(github.com/garyburd/redigo/redis)
BuildRequires:  golang(github.com/go-stomp/stomp)
BuildRequires:  golang(github.com/gocql/gocql)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/mattbaird/elastigo/lib)
BuildRequires:  golang(github.com/samuel/go-zookeeper/zk)
BuildRequires:  golang(github.com/streadway/amqp)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(gopkg.in/mgo.v2)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

