# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/dancannon/gorethink
%global goipath         gopkg.in/dancannon/gorethink.v3
%global forgeurl        https://github.com/dancannon/gorethink
Version:                3.0.5

%gometa

%global common_description %{expand:
Go language driver for RethinkDB.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go language driver for RethinkDB

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cenkalti/backoff)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/hailocab/go-hostpool)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/suite)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(gopkg.in/fatih/pool.v2)
BuildRequires:  golang(gopkg.in/gorethink/gorethink.v3)
BuildRequires:  golang(gopkg.in/gorethink/gorethink.v3/encoding)
BuildRequires:  golang(gopkg.in/gorethink/gorethink.v3/internal/compare)
BuildRequires:  golang(gopkg.in/gorethink/gorethink.v3/ql2)
BuildRequires:  golang(gopkg.in/gorethink/gorethink.v3/types)

%if %{with check}
# Tests
BuildRequires:  golang(gopkg.in/check.v1)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

