# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/open-telemetry/opentelemetry-go
%global goipath         go.opentelemetry.io/otel
%global forgeurl        https://github.com/open-telemetry/opentelemetry-go
Version:                0.20.0

%gometa

%global goaltipaths     github.com/open-telemetry/opentelemetry-go github.com/open-telemetry/opentelemetry-go-contrib/propagation/opencensus

%global common_description %{expand:
OpenTelemetry Go API and SDK.}

%global golicenses      LICENSE
%global godocs          example VERSIONING.md CHANGELOG.md CONTRIBUTING.md\\\
                        README.md RELEASING.md bridge/opencensus/README.md\\\
                        exporters/README.md\\\
                        exporters/metric/prometheus/README.md\\\
                        exporters/otlp/README.md\\\
                        exporters/trace/jaeger/README.md sdk/README.md\\\
                        website_docs/_index.md website_docs/exporting_data.md\\\
                        website_docs/getting-started.md\\\
                        website_docs/instrumentation.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        OpenTelemetry Go API and SDK

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/benbjohnson/clock)
BuildRequires:  golang(github.com/opentracing/opentracing-go)
BuildRequires:  golang(github.com/opentracing/opentracing-go/ext)
BuildRequires:  golang(github.com/opentracing/opentracing-go/log)
BuildRequires:  golang(github.com/openzipkin/zipkin-go/model)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus/promhttp)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(go.opencensus.io/metric)
BuildRequires:  golang(go.opencensus.io/metric/metricdata)
BuildRequires:  golang(go.opencensus.io/metric/metricexport)
BuildRequires:  golang(go.opencensus.io/metric/metricproducer)
BuildRequires:  golang(go.opencensus.io/resource)
BuildRequires:  golang(go.opencensus.io/stats)
BuildRequires:  golang(go.opencensus.io/stats/view)
BuildRequires:  golang(go.opencensus.io/tag)
BuildRequires:  golang(go.opencensus.io/trace)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/collector/metrics/v1)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/collector/trace/v1)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/common/v1)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/metrics/v1)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/resource/v1)
BuildRequires:  golang(go.opentelemetry.io/proto/otlp/trace/v1)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/encoding/gzip)
BuildRequires:  golang(google.golang.org/grpc/metadata)
BuildRequires:  golang(google.golang.org/protobuf/encoding/protojson)
BuildRequires:  golang(google.golang.org/protobuf/proto)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/stretchr/testify/mock)
BuildRequires:  golang(github.com/stretchr/testify/suite)
BuildRequires:  golang(go.opencensus.io/trace/tracestate)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

