# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/influxdata/flux
%global goipath         github.com/influxdata/flux
Version:                0.117.3

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          docs examples TODO.txt CONTRIBUTING.md README.md\\\
                        README-benchmarks-flux.md\\\
                        curl-format-benchmarks-flux.txt README-colm.txt\\\
                        query01-expected-colm-tableflux-expected.txt\\\
                        query02-expected-colm-tableflux-expected.txt\\\
                        query03-expected-colm-tableflux-expected.txt\\\
                        query04-expected-colm-tableflux-expected.txt\\\
                        query05-expected-colm-tableflux-expected.txt\\\
                        query06-expected-colm-tableflux-expected.txt\\\
                        query07-expected-colm-tableflux-expected.txt\\\
                        query08-expected-colm-tableflux-expected.txt\\\
                        query09-expected-colm-tableflux-expected.txt\\\
                        query10-expected-colm-tableflux-expected.txt\\\
                        query11-expected-colm-tableflux-expected.txt\\\
                        query12-expected-colm-tableflux-expected.txt\\\
                        query13-expected-colm-tableflux-expected.txt\\\
                        query14-expected-colm-tableflux-expected.txt\\\
                        query15-expected-colm-tableflux-expected.txt\\\
                        query16-expected-colm-tableflux-expected.txt\\\
                        query17-expected-colm-tableflux-expected.txt\\\
                        query18-expected-colm-tableflux-expected.txt\\\
                        query19-expected-colm-tableflux-expected.txt\\\
                        query20-expected-colm-tableflux-expected.txt\\\
                        query21-expected-colm-tableflux-expected.txt\\\
                        query22-expected-colm-tableflux-expected.txt\\\
                        query23-expected-colm-tableflux-expected.txt\\\
                        query24-expected-colm-tableflux-expected.txt\\\
                        query25-expected-colm-tableflux-expected.txt\\\
                        query26-expected-colm-tableflux-expected.txt\\\
                        README-libflux.md grammar-parser.md\\\
                        README-querytest.md README-stdlib.md\\\
                        README-stdlib-contrib.md\\\
                        README-stdlib-contrib-RohanSreerama5-naiveBayesClassifier.md\\\
                        README-stdlib-contrib-chobbs-discord.md\\\
                        README-stdlib-contrib-sranka-opsgenie.md\\\
                        README-stdlib-contrib-sranka-sensu.md\\\
                        README-stdlib-contrib-sranka-teams.md\\\
                        README-stdlib-contrib-sranka-telegram.md\\\
                        README-stdlib-contrib-tomhollingworth-events.md\\\
                        README-stdlib-contrib-bonitoo-io-tickscript.md\\\
                        README-stdlib-contrib-bonitoo-io-victorops.md\\\
                        README-stdlib-contrib-bonitoo-io-zenoss.md\\\
                        README-stdlib-contrib-rhajek-bigpanda.md\\\
                        README-stdlib-experimental-geo.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/bigtable)
BuildRequires:  golang(cloud.google.com/go/civil)
BuildRequires:  golang(github.com/andreyvit/diff)
BuildRequires:  golang(github.com/apache/arrow/go/arrow)
BuildRequires:  golang(github.com/apache/arrow/go/arrow/array)
BuildRequires:  golang(github.com/apache/arrow/go/arrow/bitutil)
BuildRequires:  golang(github.com/apache/arrow/go/arrow/math)
BuildRequires:  golang(github.com/apache/arrow/go/arrow/memory)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/adal)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure/auth)
BuildRequires:  golang(github.com/benbjohnson/immutable)
BuildRequires:  golang(github.com/benbjohnson/tmpl)
BuildRequires:  golang(github.com/bonitoo-io/go-sql-bigquery)
BuildRequires:  golang(github.com/c-bata/go-prompt)
BuildRequires:  golang(github.com/cespare/xxhash/v2)
BuildRequires:  golang(github.com/dave/jennifer/jen)
BuildRequires:  golang(github.com/denisenkom/go-mssqldb)
BuildRequires:  golang(github.com/eclipse/paho.mqtt.golang)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/gofrs/uuid)
BuildRequires:  golang(github.com/golang/geo/r1)
BuildRequires:  golang(github.com/golang/geo/s1)
BuildRequires:  golang(github.com/golang/geo/s2)
BuildRequires:  golang(github.com/google/flatbuffers/go)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(github.com/goreleaser/goreleaser)
BuildRequires:  golang(github.com/influxdata/changelog)
BuildRequires:  golang(github.com/influxdata/influxdb-client-go/v2/api)
BuildRequires:  golang(github.com/influxdata/influxdb-client-go/v2/api/http)
BuildRequires:  golang(github.com/influxdata/influxdb-client-go/v2/api/write)
BuildRequires:  golang(github.com/influxdata/line-protocol)
BuildRequires:  golang(github.com/influxdata/promql/v2)
BuildRequires:  golang(github.com/influxdata/promql/v2/pkg/labels)
BuildRequires:  golang(github.com/influxdata/tdigest)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(github.com/matttproud/golang_protobuf_extensions/pbutil)
BuildRequires:  golang(github.com/opentracing/opentracing-go)
BuildRequires:  golang(github.com/opentracing/opentracing-go/log)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/prometheus/client_model/go)
BuildRequires:  golang(github.com/prometheus/common/expfmt)
BuildRequires:  golang(github.com/prometheus/common/model)
BuildRequires:  golang(github.com/SAP/go-hdb/driver)
BuildRequires:  golang(github.com/segmentio/kafka-go)
BuildRequires:  golang(github.com/snowflakedb/gosnowflake)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/uber/athenadriver/go)
BuildRequires:  golang(github.com/uber/jaeger-client-go)
BuildRequires:  golang(go.uber.org/zap)
BuildRequires:  golang(go.uber.org/zap/zapcore)
BuildRequires:  golang(go.uber.org/zap/zaptest)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/tools/go/callgraph)
BuildRequires:  golang(golang.org/x/tools/go/callgraph/rta)
BuildRequires:  golang(golang.org/x/tools/go/packages)
BuildRequires:  golang(golang.org/x/tools/go/ssa)
BuildRequires:  golang(golang.org/x/tools/go/ssa/ssautil)
BuildRequires:  golang(gonum.org/v1/gonum/floats/scalar)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(honnef.co/go/tools/cmd/staticcheck)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/DATA-DOG/go-sqlmock)
BuildRequires:  golang(github.com/foxcpp/go-mockdns)
BuildRequires:  golang(github.com/opentracing/opentracing-go/mocktracer)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv benchmarks/flux/README.md README-benchmarks-flux.md
mv benchmarks/flux/curl-format.txt curl-format-benchmarks-flux.txt
mv colm/README.txt README-colm.txt
mv colm/tableflux/expected/query01-expected.txt query01-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query02-expected.txt query02-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query03-expected.txt query03-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query04-expected.txt query04-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query05-expected.txt query05-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query06-expected.txt query06-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query07-expected.txt query07-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query08-expected.txt query08-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query09-expected.txt query09-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query10-expected.txt query10-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query11-expected.txt query11-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query12-expected.txt query12-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query13-expected.txt query13-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query14-expected.txt query14-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query15-expected.txt query15-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query16-expected.txt query16-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query17-expected.txt query17-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query18-expected.txt query18-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query19-expected.txt query19-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query20-expected.txt query20-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query21-expected.txt query21-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query22-expected.txt query22-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query23-expected.txt query23-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query24-expected.txt query24-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query25-expected.txt query25-expected-colm-tableflux-expected.txt
mv colm/tableflux/expected/query26-expected.txt query26-expected-colm-tableflux-expected.txt
mv libflux/README.md README-libflux.md
mv parser/grammar.md grammar-parser.md
mv querytest/README.md README-querytest.md
mv stdlib/README.md README-stdlib.md
mv stdlib/contrib/README.md README-stdlib-contrib.md
mv stdlib/contrib/RohanSreerama5/naiveBayesClassifier/README.md README-stdlib-contrib-RohanSreerama5-naiveBayesClassifier.md
mv stdlib/contrib/chobbs/discord/README.md README-stdlib-contrib-chobbs-discord.md
mv stdlib/contrib/sranka/opsgenie/README.md README-stdlib-contrib-sranka-opsgenie.md
mv stdlib/contrib/sranka/sensu/README.md README-stdlib-contrib-sranka-sensu.md
mv stdlib/contrib/sranka/teams/README.md README-stdlib-contrib-sranka-teams.md
mv stdlib/contrib/sranka/telegram/README.md README-stdlib-contrib-sranka-telegram.md
mv stdlib/contrib/tomhollingworth/events/README.md README-stdlib-contrib-tomhollingworth-events.md
mv stdlib/contrib/bonitoo-io/tickscript/README.md README-stdlib-contrib-bonitoo-io-tickscript.md
mv stdlib/contrib/bonitoo-io/victorops/README.md README-stdlib-contrib-bonitoo-io-victorops.md
mv stdlib/contrib/bonitoo-io/zenoss/README.md README-stdlib-contrib-bonitoo-io-zenoss.md
mv stdlib/contrib/rhajek/bigpanda/README.md README-stdlib-contrib-rhajek-bigpanda.md
mv stdlib/experimental/geo/README.md README-stdlib-experimental-geo.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs examples TODO.txt CONTRIBUTING.md README.md README-benchmarks-flux.md
%doc curl-format-benchmarks-flux.txt README-colm.txt
%doc query01-expected-colm-tableflux-expected.txt
%doc query02-expected-colm-tableflux-expected.txt
%doc query03-expected-colm-tableflux-expected.txt
%doc query04-expected-colm-tableflux-expected.txt
%doc query05-expected-colm-tableflux-expected.txt
%doc query06-expected-colm-tableflux-expected.txt
%doc query07-expected-colm-tableflux-expected.txt
%doc query08-expected-colm-tableflux-expected.txt
%doc query09-expected-colm-tableflux-expected.txt
%doc query10-expected-colm-tableflux-expected.txt
%doc query11-expected-colm-tableflux-expected.txt
%doc query12-expected-colm-tableflux-expected.txt
%doc query13-expected-colm-tableflux-expected.txt
%doc query14-expected-colm-tableflux-expected.txt
%doc query15-expected-colm-tableflux-expected.txt
%doc query16-expected-colm-tableflux-expected.txt
%doc query17-expected-colm-tableflux-expected.txt
%doc query18-expected-colm-tableflux-expected.txt
%doc query19-expected-colm-tableflux-expected.txt
%doc query20-expected-colm-tableflux-expected.txt
%doc query21-expected-colm-tableflux-expected.txt
%doc query22-expected-colm-tableflux-expected.txt
%doc query23-expected-colm-tableflux-expected.txt
%doc query24-expected-colm-tableflux-expected.txt
%doc query25-expected-colm-tableflux-expected.txt
%doc query26-expected-colm-tableflux-expected.txt README-libflux.md
%doc grammar-parser.md README-querytest.md README-stdlib.md
%doc README-stdlib-contrib.md
%doc README-stdlib-contrib-RohanSreerama5-naiveBayesClassifier.md
%doc README-stdlib-contrib-chobbs-discord.md
%doc README-stdlib-contrib-sranka-opsgenie.md
%doc README-stdlib-contrib-sranka-sensu.md README-stdlib-contrib-sranka-teams.md
%doc README-stdlib-contrib-sranka-telegram.md
%doc README-stdlib-contrib-tomhollingworth-events.md
%doc README-stdlib-contrib-bonitoo-io-tickscript.md
%doc README-stdlib-contrib-bonitoo-io-victorops.md
%doc README-stdlib-contrib-bonitoo-io-zenoss.md
%doc README-stdlib-contrib-rhajek-bigpanda.md README-stdlib-experimental-geo.md

%gopkgfiles

%changelog

