# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/docker/distribution
%global goipath         github.com/docker/distribution
Version:                2.6.2

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          docs AUTHORS BUILDING.md CHANGELOG.md\\\
                        CONTRIBUTING.md README.md RELEASE-CHECKLIST.md\\\
                        ROADMAP.md README-contrib-apache.MD\\\
                        README-contrib-compose.md\\\
                        README-contrib-docker-integration.md\\\
                        README-project-hooks.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/corehandlers)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/cloudfront/sign)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/storage)
BuildRequires:  golang(github.com/bugsnag/bugsnag-go)
BuildRequires:  golang(github.com/docker/goamz/aws)
BuildRequires:  golang(github.com/docker/goamz/s3)
BuildRequires:  golang(github.com/docker/libtrust)
BuildRequires:  golang(github.com/garyburd/redigo/redis)
BuildRequires:  golang(github.com/gorilla/handlers)
BuildRequires:  golang(github.com/gorilla/mux)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/ncw/swift)
BuildRequires:  golang(github.com/Sirupsen/logrus)
BuildRequires:  golang(github.com/Sirupsen/logrus/formatters/logstash)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/stevvooe/resumable)
BuildRequires:  golang(github.com/stevvooe/resumable/sha256)
BuildRequires:  golang(github.com/stevvooe/resumable/sha512)
BuildRequires:  golang(github.com/yvasiyarov/gorelic)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(gopkg.in/check.v1)
BuildRequires:  golang(gopkg.in/yaml.v2)
BuildRequires:  golang(rsc.io/letsencrypt)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/ncw/swift/swifttest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv contrib/apache/README.MD README-contrib-apache.MD
mv contrib/compose/README.md README-contrib-compose.md
mv contrib/docker-integration/README.md README-contrib-docker-integration.md
mv project/hooks/README.md README-project-hooks.md

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in contrib/token-server; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs AUTHORS BUILDING.md CHANGELOG.md CONTRIBUTING.md README.md
%doc RELEASE-CHECKLIST.md ROADMAP.md README-contrib-apache.MD
%doc README-contrib-compose.md README-contrib-docker-integration.md
%doc README-project-hooks.md
%{_bindir}/*

%gopkgfiles

%changelog

