# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/kisielk/gotool
%global goipath         github.com/kisielk/gotool
Version:                1.0.0

%gometa

%global common_description %{expand:
A library of some of the utility functions provided by (but not exported) by
cmd/go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A library of some of the utility functions provided by (but not exported) by cmd/go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

