# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/dnstap/golang-dnstap
%global goipath         github.com/dnstap/golang-dnstap
Version:                0.4.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      COPYRIGHT LICENSE LICENSE-dnstap.pb
%global godocs          README README-dnstap.pb.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0 and CC0-1.0
License:        ASL 2.0 and CC0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/farsightsec/golang-framestream)
BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(google.golang.org/protobuf/proto)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)

%description
%{common_description}

%gopkg

%prep
%goprep
mv dnstap.pb/LICENSE LICENSE-dnstap.pb
mv dnstap.pb/README.md README-dnstap.pb.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYRIGHT LICENSE LICENSE-dnstap.pb
%doc README README-dnstap.pb.md

%gopkgfiles

%changelog

