# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/googleapis/google-cloud-go
%global goipath         cloud.google.com/go/firestore
%global forgeurl        https://github.com/googleapis/google-cloud-go
Version:                1.0.0
%global tag             firestore/v1.0.0
%global commit          1e706865e6dac33916479cd73e4dadc1b0935dab

%gometa

%global common_description %{expand:
Google Cloud Client Libraries for Go.}

%global golicenses      LICENSE license_test.go
%global godocs          CODE_OF_CONDUCT.md issue_template.md CHANGES.md\\\
                        CONTRIBUTING.md README.md RELEASING.md\\\
                        CHANGES-bigquery.md README-bigquery.md\\\
                        README-bigquery-benchmarks.md CHANGES-bigtable.md\\\
                        CHANGES-datastore.md README-datastore.md\\\
                        CHANGES-firestore.md examples\\\
                        README-httpreplay-cmd-httpr.md CHANGES-logging.md\\\
                        README-logging.md README-logging-apiv2.md\\\
                        README-profiler-mocks.md README-pubsub.md\\\
                        CHANGES-pubsub.md README-spanner.md\\\
                        README-spanner-spannertest.md README-storage.md\\\
                        README-vision-apiv1.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Google Cloud Client Libraries for Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/bigtable)
BuildRequires:  golang(cloud.google.com/go/bigtable/bttest)
BuildRequires:  golang(cloud.google.com/go/bigtable/internal/cbtconfig)
BuildRequires:  golang(cloud.google.com/go/bigtable/internal/option)
BuildRequires:  golang(cloud.google.com/go/bigtable/internal/stat)
BuildRequires:  golang(cloud.google.com/go/civil)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/breakpoints)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/controller)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/arch)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/dwarf)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/elf)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/local)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/server)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/debug/server/protocol)
BuildRequires:  golang(cloud.google.com/go/cmd/go-cloud-debug-agent/internal/valuecollector)
BuildRequires:  golang(cloud.google.com/go/compute/metadata)
BuildRequires:  golang(cloud.google.com/go/datastore/internal/gaepb)
BuildRequires:  golang(cloud.google.com/go/errorreporting/apiv1beta1)
BuildRequires:  golang(cloud.google.com/go/grafeas/apiv1)
BuildRequires:  golang(cloud.google.com/go/httpreplay/internal/proxy)
BuildRequires:  golang(cloud.google.com/go/iam)
BuildRequires:  golang(cloud.google.com/go/internal)
BuildRequires:  golang(cloud.google.com/go/internal/btree)
BuildRequires:  golang(cloud.google.com/go/internal/fields)
BuildRequires:  golang(cloud.google.com/go/internal/optional)
BuildRequires:  golang(cloud.google.com/go/internal/protostruct)
BuildRequires:  golang(cloud.google.com/go/internal/testutil)
BuildRequires:  golang(cloud.google.com/go/internal/trace)
BuildRequires:  golang(cloud.google.com/go/internal/version)
BuildRequires:  golang(cloud.google.com/go/logging)
BuildRequires:  golang(cloud.google.com/go/logging/apiv2)
BuildRequires:  golang(cloud.google.com/go/logging/internal)
BuildRequires:  golang(cloud.google.com/go/longrunning)
BuildRequires:  golang(cloud.google.com/go/longrunning/autogen)
BuildRequires:  golang(cloud.google.com/go/profiler)
BuildRequires:  golang(cloud.google.com/go/pubsub)
BuildRequires:  golang(cloud.google.com/go/pubsub/apiv1)
BuildRequires:  golang(cloud.google.com/go/pubsub/internal/distribution)
BuildRequires:  golang(cloud.google.com/go/pubsub/loadtest)
BuildRequires:  golang(cloud.google.com/go/pubsub/loadtest/pb)
BuildRequires:  golang(cloud.google.com/go/rpcreplay/proto/rpcreplay)
BuildRequires:  golang(cloud.google.com/go/spanner)
BuildRequires:  golang(cloud.google.com/go/spanner/apiv1)
BuildRequires:  golang(cloud.google.com/go/spanner/internal/backoff)
BuildRequires:  golang(cloud.google.com/go/spanner/internal/benchwrapper/proto)
BuildRequires:  golang(cloud.google.com/go/spanner/spansql)
BuildRequires:  golang(cloud.google.com/go/storage)
BuildRequires:  golang(cloud.google.com/go/storage/internal/benchwrapper/proto)
BuildRequires:  golang(github.com/golang/mock/gomock)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/duration)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/empty)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/struct)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/wrappers)
BuildRequires:  golang(github.com/google/btree)
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/martian)
BuildRequires:  golang(github.com/google/martian/fifo)
BuildRequires:  golang(github.com/google/martian/httpspec)
BuildRequires:  golang(github.com/google/martian/martianhttp)
BuildRequires:  golang(github.com/google/martian/martianlog)
BuildRequires:  golang(github.com/google/martian/mitm)
BuildRequires:  golang(github.com/google/pprof/profile)
BuildRequires:  golang(github.com/googleapis/gax-go/v2)
BuildRequires:  golang(go.opencensus.io/plugin/ocgrpc)
BuildRequires:  golang(go.opencensus.io/stats)
BuildRequires:  golang(go.opencensus.io/stats/view)
BuildRequires:  golang(go.opencensus.io/tag)
BuildRequires:  golang(go.opencensus.io/trace)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)
BuildRequires:  golang(golang.org/x/oauth2/jwt)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/sync/semaphore)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(golang.org/x/time/rate)
BuildRequires:  golang(google.golang.org/api/bigquery/v2)
BuildRequires:  golang(google.golang.org/api/clouddebugger/v2)
BuildRequires:  golang(google.golang.org/api/cloudresourcemanager/v1)
BuildRequires:  golang(google.golang.org/api/compute/v1)
BuildRequires:  golang(google.golang.org/api/container/v1)
BuildRequires:  golang(google.golang.org/api/googleapi)
BuildRequires:  golang(google.golang.org/api/iterator)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(google.golang.org/api/storage/v1)
BuildRequires:  golang(google.golang.org/api/support/bundler)
BuildRequires:  golang(google.golang.org/api/translate/v2)
BuildRequires:  golang(google.golang.org/api/transport)
BuildRequires:  golang(google.golang.org/api/transport/grpc)
BuildRequires:  golang(google.golang.org/api/transport/http)
BuildRequires:  golang(google.golang.org/genproto/googleapis/api/expr/v1alpha1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/api/label)
BuildRequires:  golang(google.golang.org/genproto/googleapis/api/metric)
BuildRequires:  golang(google.golang.org/genproto/googleapis/api/monitoredres)
BuildRequires:  golang(google.golang.org/genproto/googleapis/appengine/logging/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/bigtable/admin/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/bigtable/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/asset/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/asset/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/asset/v1p2beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/audit)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/automl/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/bigquery/datatransfer/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/bigquery/storage/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/dataproc/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/dataproc/v1beta2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/dialogflow/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/iot/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/irm/v1alpha2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/kms/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/language/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/language/v1beta2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/oslogin/common)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/oslogin/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/oslogin/v1beta)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/phishingprotection/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/recaptchaenterprise/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/redis/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/redis/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/scheduler/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/scheduler/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/securitycenter/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/securitycenter/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/speech/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/speech/v1p1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/talent/v4beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/tasks/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/tasks/v2beta2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/tasks/v2beta3)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/texttospeech/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/videointelligence/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/videointelligence/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/videointelligence/v1beta2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/vision/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/vision/v1p1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/webrisk/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/container/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/datastore/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/clouddebugger/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/clouderrorreporting/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/cloudprofiler/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/cloudtrace/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/cloudtrace/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/containeranalysis/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/containeranalysis/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/devtools/containeranalysis/v1beta1/grafeas)
BuildRequires:  golang(google.golang.org/genproto/googleapis/firestore/admin/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/firestore/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/firestore/v1beta1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/grafeas/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/iam/admin/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/iam/credentials/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/iam/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/logging/type)
BuildRequires:  golang(google.golang.org/genproto/googleapis/logging/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/longrunning)
BuildRequires:  golang(google.golang.org/genproto/googleapis/monitoring/v3)
BuildRequires:  golang(google.golang.org/genproto/googleapis/privacy/dlp/v2)
BuildRequires:  golang(google.golang.org/genproto/googleapis/pubsub/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/code)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/errdetails)
BuildRequires:  golang(google.golang.org/genproto/googleapis/rpc/status)
BuildRequires:  golang(google.golang.org/genproto/googleapis/spanner/admin/database/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/spanner/admin/instance/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/spanner/v1)
BuildRequires:  golang(google.golang.org/genproto/googleapis/type/latlng)
BuildRequires:  golang(google.golang.org/genproto/protobuf/field_mask)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/credentials)
BuildRequires:  golang(google.golang.org/grpc/keepalive)
BuildRequires:  golang(google.golang.org/grpc/metadata)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(rsc.io/binaryregexp)

%if %{with check}
# Tests
BuildRequires:  golang(cloud.google.com/go/bigtable/internal/conformance)
BuildRequires:  golang(cloud.google.com/go/bigtable/internal/mockserver)
BuildRequires:  golang(cloud.google.com/go/httpreplay)
BuildRequires:  golang(cloud.google.com/go/internal/pretty)
BuildRequires:  golang(cloud.google.com/go/internal/uid)
BuildRequires:  golang(cloud.google.com/go/kms/apiv1)
BuildRequires:  golang(cloud.google.com/go/logging/internal/testing)
BuildRequires:  golang(cloud.google.com/go/profiler/mocks)
BuildRequires:  golang(cloud.google.com/go/profiler/proftest)
BuildRequires:  golang(cloud.google.com/go/profiler/testdata)
BuildRequires:  golang(cloud.google.com/go/pubsub/pstest)
BuildRequires:  golang(cloud.google.com/go/rpcreplay)
BuildRequires:  golang(cloud.google.com/go/rpcreplay/proto/intstore)
BuildRequires:  golang(cloud.google.com/go/spanner/admin/database/apiv1)
BuildRequires:  golang(cloud.google.com/go/spanner/internal/testutil)
BuildRequires:  golang(cloud.google.com/go/storage/internal/test/conformance)
BuildRequires:  golang(github.com/golang/protobuf/jsonpb)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
BuildRequires:  golang(google.golang.org/api/iterator/testing)
BuildRequires:  golang(google.golang.org/api/logging/v2)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv bigquery/CHANGES.md CHANGES-bigquery.md
mv bigquery/README.md README-bigquery.md
mv bigquery/benchmarks/README.md README-bigquery-benchmarks.md
mv bigtable/CHANGES.md CHANGES-bigtable.md
mv datastore/CHANGES.md CHANGES-datastore.md
mv datastore/README.md README-datastore.md
mv firestore/CHANGES.md CHANGES-firestore.md
mv httpreplay/cmd/httpr/README.md README-httpreplay-cmd-httpr.md
mv logging/CHANGES.md CHANGES-logging.md
mv logging/README.md README-logging.md
mv logging/apiv2/README.md README-logging-apiv2.md
mv profiler/mocks/README.md README-profiler-mocks.md
mv pubsub/README.md README-pubsub.md
mv pubsub/CHANGES.md CHANGES-pubsub.md
mv spanner/README.md README-spanner.md
mv spanner/spannertest/README.md README-spanner-spannertest.md
mv storage/README.md README-storage.md
mv vision/apiv1/README.md README-vision-apiv1.md

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in bigquery/benchmarks profiler/busybench; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE license_test.go
%doc CODE_OF_CONDUCT.md issue_template.md CHANGES.md CONTRIBUTING.md README.md
%doc RELEASING.md CHANGES-bigquery.md README-bigquery.md
%doc README-bigquery-benchmarks.md CHANGES-bigtable.md CHANGES-datastore.md
%doc README-datastore.md CHANGES-firestore.md examples
%doc README-httpreplay-cmd-httpr.md CHANGES-logging.md README-logging.md
%doc README-logging-apiv2.md README-profiler-mocks.md README-pubsub.md
%doc CHANGES-pubsub.md README-spanner.md README-spanner-spannertest.md
%doc README-storage.md README-vision-apiv1.md
%{_bindir}/*

%gopkgfiles

%changelog

