# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/facebookgo/freeport
%global goipath         github.com/facebookgo/freeport
%global commit          d4adf43b75b9357dc7775f033e807a3411591522

%gometa

%global common_description %{expand:
A Go library to find a free port.}

%global golicenses      license
%global godocs          readme.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Go library to find a free port

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

