# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/huaweicloud/golangsdk
%global goipath         github.com/huaweicloud/golangsdk
%global commit          c90ae4249a7119416d3365507fbc90cd29954707

%gometa

%global common_description %{expand:
Golangsdk: this is a sdk only using by inner projects. please refer to
https://github.com/huaweicloud/huaweicloud-sdk-go.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md FAQ.md MIGRATING.md README.md\\\
                        STYLEGUIDE.md acceptance/README.md\\\
                        openstack/antiddos/v1/antiddos/API-cn.md\\\
                        openstack/antiddos/v1/antiddos/API-en.md\\\
                        openstack/antiddos/v2/alarmreminding/API-cn.md\\\
                        openstack/antiddos/v2/alarmreminding/API-en.md\\\
                        openstack/imageservice/v2/README.md\\\
                        openstack/obs/CHANGELOG openstack/obs/README.MD

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Golangsdk: this is a sdk only using by inner projects. please refer to https://github.com/huaweicloud/huaweicloud-sdk-go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(golang.org/x/crypto/ssh)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in openstack/dcs/v1/maintainwindows openstack/dms/v1/maintainwindows; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md FAQ.md MIGRATING.md README.md STYLEGUIDE.md
%doc acceptance/README.md openstack/antiddos/v1/antiddos/API-cn.md
%doc openstack/antiddos/v1/antiddos/API-en.md
%doc openstack/antiddos/v2/alarmreminding/API-cn.md
%doc openstack/antiddos/v2/alarmreminding/API-en.md
%doc openstack/imageservice/v2/README.md openstack/obs/CHANGELOG
%doc openstack/obs/README.MD
%{_bindir}/*

%gopkgfiles

%changelog

