# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/google/rpmpack
%global goipath         github.com/google/rpmpack
%global commit          dc539ef4f2ea1c53ab359280cadc7249f2fb3e61

%gometa

%global common_description %{expand:
Rpmpack (tar2rpm) - package rpms in pure golang or cli.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md content1-example_bazel.txt

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Rpmpack (tar2rpm) - package rpms in pure golang or cli

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cavaliercoder/go-cpio)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/ulikunitz/xz)
BuildRequires:  golang(github.com/ulikunitz/xz/lzma)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv example_bazel/content1.txt content1-example_bazel.txt

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md README.md content1-example_bazel.txt
%{_bindir}/*

%gopkgfiles

%changelog

