# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/olivere/elastic
%global goipath         gopkg.in/olivere/elastic.v3
%global forgeurl        https://github.com/olivere/elastic
Version:                3.0.75

%gometa

%global goaltipaths     github.com/olivere/elastic

%global common_description %{expand:
Elasticsearch client for Go.}

%global golicenses      LICENSE LICENSE-backoff LICENSE-uritemplates
%global godocs          CHANGELOG-3.0.md CODE_OF_CONDUCT.md\\\
                        ISSUE_TEMPLATE.md README.md CONTRIBUTING.md\\\
                        CONTRIBUTORS README-cluster-test.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Elasticsearch client for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/fortytw2/leaktest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv backoff/LICENSE LICENSE-backoff
mv uritemplates/LICENSE LICENSE-uritemplates
mv cluster-test/README.md README-cluster-test.md

%build
for cmd in cluster-test; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-backoff LICENSE-uritemplates
%doc CHANGELOG-3.0.md CODE_OF_CONDUCT.md ISSUE_TEMPLATE.md README.md
%doc CONTRIBUTING.md CONTRIBUTORS README-cluster-test.md
%{_bindir}/*

%gopkgfiles

%changelog

