# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/DataDog/gostackparse
%global goipath         github.com/DataDog/gostackparse
Version:                0.5.0

%gometa

%global common_description %{expand:
Package gostackparse parses goroutines stack traces as produced by panic() or
debug.Stack() at ~300 MiB/s.}

%global golicenses      LICENSE-3rdparty.csv LICENSE-APACHE LICENSE-BSD3\\\
                        LICENSE
%global godocs          example CONTRIBUTING.md README.md\\\
                        cgo-test-fixtures.txt empty_input-test-fixtures.txt\\\
                        empty_stack-test-fixtures.txt\\\
                        errorhandling-test-fixtures.txt\\\
                        frameselided-test-fixtures.txt\\\
                        frameselided_goroutine-test-fixtures.txt\\\
                        lockedm-test-fixtures.txt\\\
                        partial_createdby-test-fixtures.txt\\\
                        partial_stack-test-fixtures.txt\\\
                        waitsince-test-fixtures.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        Package gostackparse parses goroutines stack traces as produced by panic() or debug.Stack() at ~300 MiB/s

# Upstream license specification: Apache-2.0 and BSD-3-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv test-fixtures/cgo.txt cgo-test-fixtures.txt
mv test-fixtures/empty_input.txt empty_input-test-fixtures.txt
mv test-fixtures/empty_stack.txt empty_stack-test-fixtures.txt
mv test-fixtures/errorhandling.txt errorhandling-test-fixtures.txt
mv test-fixtures/frameselided.txt frameselided-test-fixtures.txt
mv test-fixtures/frameselided_goroutine.txt frameselided_goroutine-test-fixtures.txt
mv test-fixtures/lockedm.txt lockedm-test-fixtures.txt
mv test-fixtures/partial_createdby.txt partial_createdby-test-fixtures.txt
mv test-fixtures/partial_stack.txt partial_stack-test-fixtures.txt
mv test-fixtures/waitsince.txt waitsince-test-fixtures.txt

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in test-fixtures; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE-3rdparty.csv LICENSE-APACHE LICENSE-BSD3 LICENSE
%doc example CONTRIBUTING.md README.md cgo-test-fixtures.txt
%doc empty_input-test-fixtures.txt empty_stack-test-fixtures.txt
%doc errorhandling-test-fixtures.txt frameselided-test-fixtures.txt
%doc frameselided_goroutine-test-fixtures.txt lockedm-test-fixtures.txt
%doc partial_createdby-test-fixtures.txt partial_stack-test-fixtures.txt
%doc waitsince-test-fixtures.txt
%{_bindir}/*

%gopkgfiles

%changelog

