# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/opencontainers/specs
%global goipath         github.com/opencontainers/specs
Version:                1.0.2

%gometa

%global common_description %{expand:
OCI Runtime Specification.}

%global golicenses      LICENSE
%global godocs          ChangeLog GOVERNANCE.md RELEASES.md bundle.md config-\\\
                        solaris.md config-vm.md glossary.md principles.md\\\
                        runtime-linux.md spec.md style.md README.md config-\\\
                        linux.md config-windows.md config.md\\\
                        implementations.md runtime.md schema/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        OCI Runtime Specification

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/xeipuuv/gojsonschema)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in schema .tool; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc ChangeLog GOVERNANCE.md RELEASES.md bundle.md config-solaris.md
%doc config-vm.md glossary.md principles.md runtime-linux.md spec.md style.md
%doc README.md config-linux.md config-windows.md config.md implementations.md
%doc runtime.md schema/README.md
%{_bindir}/*

%gopkgfiles

%changelog

