# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/natefinch/atomic
%global goipath         github.com/natefinch/atomic
%global commit          18c0533a5b0940dce8ed0747c81dfa2150143815

%gometa

%global common_description %{expand:
package atomic provides functions to atomically change files.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        package atomic provides functions to atomically change files

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

