# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/flynn-archive/go-shlex
%global goipath         github.com/flynn-archive/go-shlex
%global commit          3f9db97f856818214da2e1057f8ad84803971cff

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      COPYING
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

