# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/criteo/haproxy-spoe-go
%global goipath         github.com/criteo/haproxy-spoe-go
Version:                1.0.6

%gometa

%global common_description %{expand:
An implementation of the SPOP protocol in Go.
https://www.haproxy.org/download/2.0/doc/SPOE.txt.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        An implementation of the SPOP protocol in Go. https://www.haproxy.org/download/2.0/doc/SPOE.txt

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/sirupsen/logrus)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

