# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/ory/dockertest
%global goipath         github.com/ory/dockertest/v3
%global forgeurl        https://github.com/ory/dockertest
Version:                3.6.5

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE DOCKER-LICENSE-docker LICENSE-docker
%global godocs          docs examples README.md SECURITY.md CONTRIBUTING.md\\\
                        AUTHORS-docker README-docker.markdown\\\
                        README-docker-pkg.md README-docker-pkg-archive.md\\\
                        README-docker-types-versions.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0 and BSD-2-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cenkalti/backoff/v4)
BuildRequires:  golang(github.com/containerd/continuity/pathdriver)
BuildRequires:  golang(github.com/docker/go-connections/nat)
BuildRequires:  golang(github.com/docker/go-units)
BuildRequires:  golang(github.com/moby/term)
BuildRequires:  golang(github.com/Nvveen/Gotty)
BuildRequires:  golang(github.com/opencontainers/image-spec/specs-go/v1)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/user)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(gotest.tools/v3/assert)
BuildRequires:  golang(gotest.tools/v3/assert/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv docker/DOCKER-LICENSE DOCKER-LICENSE-docker
mv docker/LICENSE LICENSE-docker
mv docker/AUTHORS AUTHORS-docker
mv docker/README.markdown README-docker.markdown
mv docker/pkg/README.md README-docker-pkg.md
mv docker/pkg/archive/README.md README-docker-pkg-archive.md
mv docker/types/versions/README.md README-docker-types-versions.md

%build
for cmd in docker/pkg/archive; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE DOCKER-LICENSE-docker LICENSE-docker
%doc docs examples README.md SECURITY.md CONTRIBUTING.md AUTHORS-docker
%doc README-docker.markdown README-docker-pkg.md README-docker-pkg-archive.md
%doc README-docker-types-versions.md
%{_bindir}/*

%gopkgfiles

%changelog

