# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mellium/sasl
%global goipath         mellium.im/sasl
%global forgeurl        https://github.com/mellium/sasl
Version:                0.2.1

%gometa

%global common_description %{expand:
An implementation of the Simple Authentication and Security Layer (SASL).}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        An implementation of the Simple Authentication and Security Layer (SASL)

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/crypto/pbkdf2)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

