# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/packethost/packngo
%global goipath         github.com/packethost/packngo
Version:                0.15.0

%gometa

%global common_description %{expand:
A Golang client for the Equinix Metal API. (Packet is now Equinix Metal).}

%global golicenses      LICENSE.txt
%global godocs          examples CHANGELOG.md CONTRIBUTING.md OWNERS.md\\\
                        README.md RELEASE.md SUPPORT.md code-of-conduct.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Golang client for the Equinix Metal API. (Packet is now Equinix Metal)

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/dnaeon/go-vcr/cassette)
BuildRequires:  golang(github.com/dnaeon/go-vcr/recorder)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(golang.org/x/crypto/ssh)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

