# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/moby/spdystream
%global goipath         github.com/moby/spdystream
Version:                0.2.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE NOTICE
%global godocs          CONTRIBUTING.md README.md\\\
                        scripts/validate/template/bash.txt\\\
                        scripts/validate/template/dockerfile.txt\\\
                        scripts/validate/template/go.txt\\\
                        scripts/validate/template/makefile.txt

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gorilla/websocket)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

