# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/tonistiigi/fifo
%global goipath         github.com/tonistiigi/fifo
%global commit          650e8a8a179d040123db61f016cb133143e7a581

%gometa

%global common_description %{expand:
Fifo pkg for Go.}

%global golicenses      LICENSE
%global godocs          readme.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Fifo pkg for Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

