# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/dnstap/golang-dnstap
%global goipath         github.com/dnstap/golang-dnstap
Version:                0.4.0

%gometa

%global common_description %{expand:
Flexible, structured event replication format for DNS servers (command-line
tool and Golang package).}

%global golicenses      COPYRIGHT LICENSE dnstap.pb/LICENSE
%global godocs          README dnstap.pb/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Flexible, structured event replication format for DNS servers (command-line tool and Golang package)

# Upstream license specification: Apache-2.0 and CC0-1.0
License:        ASL 2.0 and CC0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/farsightsec/golang-framestream)
BuildRequires:  golang(github.com/miekg/dns)
BuildRequires:  golang(google.golang.org/protobuf/proto)
BuildRequires:  golang(google.golang.org/protobuf/reflect/protoreflect)
BuildRequires:  golang(google.golang.org/protobuf/runtime/protoimpl)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in dnstap; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYRIGHT LICENSE dnstap.pb/LICENSE
%doc README dnstap.pb/README.md
%{_bindir}/*

%gopkgfiles

%changelog

