# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/dancannon/gorethink
%global goipath         github.com/dancannon/gorethink
Version:                6.2.1

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/hailocab/go-hostpool)
BuildRequires:  golang(github.com/opentracing/opentracing-go)
BuildRequires:  golang(github.com/opentracing/opentracing-go/ext)
BuildRequires:  golang(github.com/opentracing/opentracing-go/log)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/suite)
BuildRequires:  golang(golang.org/x/crypto/pbkdf2)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(gopkg.in/cenkalti/backoff.v2)
BuildRequires:  golang(gopkg.in/check.v1)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6/encoding)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6/internal/compare)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6/ql2)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6/types)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/opentracing/opentracing-go/mocktracer)
BuildRequires:  golang(github.com/stretchr/testify/mock)
BuildRequires:  golang(gopkg.in/rethinkdb/rethinkdb-go.v6/internal/integration/tests)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

