# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/Sirupsen/logrus
%global goipath         github.com/Sirupsen/logrus
Version:                0.10.0

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.md README.md\\\
                        hooks/syslog/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(gopkg.in/gemnasium/logrus-airbrake-hook.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

