# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mitchellh/pointerstructure
%global goipath         github.com/mitchellh/pointerstructure
Version:                1.2.0

%gometa

%global common_description %{expand:
Go library for addressing and reading/writing a specific value within any Go
structure using a string syntax.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library for addressing and reading/writing a specific value within any Go structure using a string syntax

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/mitchellh/mapstructure)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

