# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/ory-am/dockertest
%global goipath         github.com/ory-am/dockertest
Version:                3.6.5

%gometa

%global common_description %{expand:
Write better integration tests! Dockertest helps you boot up ephermal docker
images for your Go tests with minimal work.}

%global golicenses      LICENSE docker/DOCKER-LICENSE docker/LICENSE
%global godocs          docs examples README.md SECURITY.md CONTRIBUTING.md\\\
                        docker/AUTHORS docker/README.markdown\\\
                        docker/pkg/README.md docker/pkg/archive/README.md\\\
                        docker/types/versions/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Write better integration tests! Dockertest helps you boot up ephermal docker images for your Go tests with minimal work

# Upstream license specification: Apache-2.0 and BSD-2-Clause
License:        ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cenkalti/backoff/v4)
BuildRequires:  golang(github.com/containerd/continuity/pathdriver)
BuildRequires:  golang(github.com/docker/go-connections/nat)
BuildRequires:  golang(github.com/docker/go-units)
BuildRequires:  golang(github.com/moby/term)
BuildRequires:  golang(github.com/Nvveen/Gotty)
BuildRequires:  golang(github.com/opencontainers/image-spec/specs-go/v1)
BuildRequires:  golang(github.com/opencontainers/runc/libcontainer/user)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/opts)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/archive)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/fileutils)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/homedir)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/idtools)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/ioutils)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/jsonmessage)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/mount)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/pools)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/stdcopy)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/pkg/system)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/blkiodev)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/container)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/filters)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/mount)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/network)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/registry)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/strslice)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/versions)
BuildRequires:  golang(github.com/ory/dockertest/v3/docker/types/versions/v1p20)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
BuildRequires:  golang(gotest.tools/v3/assert)
BuildRequires:  golang(gotest.tools/v3/assert/cmp)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in docker/pkg/archive; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE docker/DOCKER-LICENSE docker/LICENSE
%doc docs examples README.md SECURITY.md CONTRIBUTING.md docker/AUTHORS
%doc docker/README.markdown docker/pkg/README.md docker/pkg/archive/README.md
%doc docker/types/versions/README.md
%{_bindir}/*

%gopkgfiles

%changelog

