# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/mitchellh/go-ps
%global goipath         github.com/mitchellh/go-ps
Version:                1.0.0

%gometa

%global common_description %{expand:
Find, list, and inspect processes from Go (golang).}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Find, list, and inspect processes from Go (golang)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog

