# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/hashicorp/vault
%global goipath         github.com/hashicorp/vault/api
%global forgeurl        https://github.com/hashicorp/vault
Version:                1.1.0

%gometa

%global goaltipaths     github.com/hashicorp/vault

%global common_description %{expand:
A tool for secrets management, encryption as a service, and privileged access
management.}

%global golicenses      LICENSE license-ui-app-adapters.js\\\
                        license-info-ui-app-components.js\\\
                        license-ui-app-controllers-vault-cluster.js\\\
                        license-ui-app-models.js\\\
                        license-ui-app-routes-vault-cluster.js\\\
                        license-info-ui-app-templates-components.hbs\\\
                        license-ui-app-templates-vault-cluster.hbs\\\
                        LICENSE-website.md\\\
                        license.html-website-source-api-system.md
%global godocs          CONTRIBUTING.md CHANGELOG.md README.md\\\
                        generate-builtin-credential-cert-test-fixtures.txt\\\
                        README-physical-foundationdb.md\\\
                        README-plugins-database-mssql.md README-ui.md\\\
                        robots-ui-public.txt README-website.md docs\\\
                        404.html-website-source.md robots-website-source.txt\\\
                        libraries.html-website-source-api.md\\\
                        overview.html-website-source-api.md\\\
                        relatedtools.html-website-source-api.md\\\
                        index.html-website-source-api-auth.md\\\
                        index.html-website-source-api-auth-app-id.md\\\
                        index.html-website-source-api-auth-approle.md\\\
                        index.html-website-source-api-auth-aws.md\\\
                        index.html-website-source-api-auth-azure.md\\\
                        index.html-website-source-api-auth-cert.md\\\
                        index.html-website-source-api-auth-gcp.md\\\
                        index.html-website-source-api-auth-github.md\\\
                        index.html-website-source-api-auth-kubernetes.md\\\
                        index.html-website-source-api-auth-ldap.md\\\
                        index.html-website-source-api-auth-okta.md\\\
                        index.html-website-source-api-auth-radius.md\\\
                        index.html-website-source-api-auth-token.md\\\
                        index.html-website-source-api-auth-userpass.md\\\
                        index.html-website-source-api-auth-alicloud.md\\\
                        index.html-website-source-api-auth-jwt.md\\\
                        index_beta.html-website-source-api-auth-jwt.md\\\
                        index.html-website-source-api-secret.md\\\
                        index.html-website-source-api-secret-ad.md\\\
                        index.html-website-source-api-secret-aws.md\\\
                        index.html-website-source-api-secret-cassandra.md\\\
                        index.html-website-source-api-secret-consul.md\\\
                        index.html-website-source-api-secret-cubbyhole.md\\\
                        cassandra.html-website-source-api-secret-databases.md\\\
                        hanadb.html-website-source-api-secret-databases.md\\\
                        index.html-website-source-api-secret-databases.md\\\
                        influxdb.html-website-source-api-secret-databases.md\\\
                        mongodb.html-website-source-api-secret-databases.md\\\
                        mssql.html-website-source-api-secret-databases.md\\\
                        mysql-maria.html-website-source-api-secret-databases.md\\\
                        oracle.html-website-source-api-secret-databases.md\\\
                        postgresql.html-website-source-api-secret-databases.md\\\
                        index.html-website-source-api-secret-gcp.md\\\
                        entity-alias.html-website-source-api-secret-identity.md\\\
                        entity.html-website-source-api-secret-identity.md\\\
                        group-alias.html-website-source-api-secret-identity.md\\\
                        group.html-website-source-api-secret-identity.md\\\
                        identity-groups.html-website-source-api-secret-identity.md\\\
                        index.html-website-source-api-secret-identity.md\\\
                        lookup.html-website-source-api-secret-identity.md\\\
                        index.html-website-source-api-secret-kv.md\\\
                        kv-v1.html-website-source-api-secret-kv.md\\\
                        kv-v2.html-website-source-api-secret-kv.md\\\
                        index.html-website-source-api-secret-mongodb.md\\\
                        index.html-website-source-api-secret-mssql.md\\\
                        index.html-website-source-api-secret-mysql.md\\\
                        index.html-website-source-api-secret-nomad.md\\\
                        index.html-website-source-api-secret-pki.md\\\
                        index.html-website-source-api-secret-postgresql.md\\\
                        index.html-website-source-api-secret-rabbitmq.md\\\
                        index.html-website-source-api-secret-ssh.md\\\
                        index.html-website-source-api-secret-totp.md\\\
                        index.html-website-source-api-secret-transit.md\\\
                        index.html-website-source-api-secret-alicloud.md\\\
                        index.html-website-source-api-secret-azure.md\\\
                        index.html-website-source-api-secret-gcpkms.md\\\
                        init.html-website-source-api-system.md\\\
                        internal-specs-openapi.html-website-source-api-system.md\\\
                        key-status.html-website-source-api-system.md\\\
                        leader.html-website-source-api-system.md\\\
                        leases.html-website-source-api-system.md\\\
                        mounts.html-website-source-api-system.md\\\
                        namespaces.html-website-source-api-system.md\\\
                        plugins-catalog.html-website-source-api-system.md\\\
                        plugins-reload-backend.html-website-source-api-system.md\\\
                        policies.html-website-source-api-system.md\\\
                        policy.html-website-source-api-system.md\\\
                        raw.html-website-source-api-system.md\\\
                        rekey-recovery-key.html-website-source-api-system.md\\\
                        rekey.html-website-source-api-system.md\\\
                        remount.html-website-source-api-system.md\\\
                        rotate.html-website-source-api-system.md\\\
                        seal-status.html-website-source-api-system.md\\\
                        seal.html-website-source-api-system.md\\\
                        step-down.html-website-source-api-system.md\\\
                        tools.html-website-source-api-system.md\\\
                        unseal.html-website-source-api-system.md\\\
                        wrapping-lookup.html-website-source-api-system.md\\\
                        wrapping-rewrap.html-website-source-api-system.md\\\
                        wrapping-unwrap.html-website-source-api-system.md\\\
                        wrapping-wrap.html-website-source-api-system.md\\\
                        audit-hash.html-website-source-api-system.md\\\
                        audit.html-website-source-api-system.md\\\
                        auth.html-website-source-api-system.md\\\
                        capabilities-accessor.html-website-source-api-system.md\\\
                        capabilities-self.html-website-source-api-system.md\\\
                        capabilities.html-website-source-api-system.md\\\
                        config-auditing.html-website-source-api-system.md\\\
                        config-control-group.html-website-source-api-system.md\\\
                        config-cors.html-website-source-api-system.md\\\
                        config-ui.html-website-source-api-system.md\\\
                        control-group.html-website-source-api-system.md\\\
                        generate-root.html-website-source-api-system.md\\\
                        health.html-website-source-api-system.md\\\
                        index.html-website-source-api-system.md\\\
                        internal-ui-mounts.html-website-source-api-system.md\\\
                        duo.html-website-source-api-system-mfa.md\\\
                        index.html-website-source-api-system-mfa.md\\\
                        okta.html-website-source-api-system-mfa.md\\\
                        pingid.html-website-source-api-system-mfa.md\\\
                        totp.html-website-source-api-system-mfa.md\\\
                        index.html-website-source-api-system-replication.md\\\
                        replication-dr.html-website-source-api-system-replication.md\\\
                        replication-performance.html-website-source-api-system-replication.md\\\
                        index.html-website-source-guides.md\\\
                        index.html-website-source-guides-encryption.md\\\
                        spring-demo.html-website-source-guides-encryption.md\\\
                        transit-rewrap.html-website-source-guides-encryption.md\\\
                        transit.html-website-source-guides-encryption.md\\\
                        index.html-website-source-guides-getting-started.md\\\
                        approle-trusted-entities.html-website-source-guides-identity.md\\\
                        authentication.html-website-source-guides-identity.md\\\
                        control-groups.html-website-source-guides-identity.md\\\
                        identity.html-website-source-guides-identity.md\\\
                        index.html-website-source-guides-identity.md\\\
                        lease.html-website-source-guides-identity.md\\\
                        policies.html-website-source-guides-identity.md\\\
                        policy-templating.html-website-source-guides-identity.md\\\
                        secure-intro.html-website-source-guides-identity.md\\\
                        sentinel.html-website-source-guides-identity.md\\\
                        autounseal-aws-kms.html-website-source-guides-operations.md\\\
                        deployment-guide.html-website-source-guides-operations.md\\\
                        disaster-recovery.html-website-source-guides-operations.md\\\
                        generate-root.html-website-source-guides-operations.md\\\
                        index.html-website-source-guides-operations.md\\\
                        monitoring.html-website-source-guides-operations.md\\\
                        mount-filter.html-website-source-guides-operations.md\\\
                        multi-tenant.html-website-source-guides-operations.md\\\
                        performance-nodes.html-website-source-guides-operations.md\\\
                        plugin-backends.html-website-source-guides-operations.md\\\
                        production.html-website-source-guides-operations.md\\\
                        reference-architecture.html-website-source-guides-operations.md\\\
                        rekeying-and-rotating.html-website-source-guides-operations.md\\\
                        replication.html-website-source-guides-operations.md\\\
                        seal-wrap.html-website-source-guides-operations.md\\\
                        vault-ha-consul.html-website-source-guides-operations.md\\\
                        app-integration.html-website-source-guides-secret-mgmt.md\\\
                        cubbyhole.html-website-source-guides-secret-mgmt.md\\\
                        db-root-rotation.html-website-source-guides-secret-mgmt.md\\\
                        dynamic-secrets.html-website-source-guides-secret-mgmt.md\\\
                        index.html-website-source-guides-secret-mgmt.md\\\
                        pki-engine.html-website-source-guides-secret-mgmt.md\\\
                        ssh-otp.html-website-source-guides-secret-mgmt.md\\\
                        static-secrets.html-website-source-guides-secret-mgmt.md\\\
                        versioned-kv.html-website-source-guides-secret-mgmt.md\\\
                        apis.html-website-source-intro-getting-started.md\\\
                        authentication.html-website-source-intro-getting-started.md\\\
                        deploy.html-website-source-intro-getting-started.md\\\
                        dev-server.html-website-source-intro-getting-started.md\\\
                        dynamic-secrets.html-website-source-intro-getting-started.md\\\
                        first-secret.html-website-source-intro-getting-started.md\\\
                        help.html-website-source-intro-getting-started.md\\\
                        index.html-website-source-intro-getting-started.md\\\
                        next-steps.html-website-source-intro-getting-started.md\\\
                        policies.html-website-source-intro-getting-started.md\\\
                        secrets-engines.html-website-source-intro-getting-started.md\\\
                        README-terraform-aws.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A tool for secrets management, encryption as a service, and privileged access management

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(cloud.google.com/go/kms/apiv1)
BuildRequires:  golang(cloud.google.com/go/spanner)
BuildRequires:  golang(cloud.google.com/go/storage)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials/providers)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/services/kms)
BuildRequires:  golang(github.com/aliyun/aliyun-oss-go-sdk/oss)
BuildRequires:  golang(github.com/armon/go-metrics)
BuildRequires:  golang(github.com/armon/go-metrics/circonus)
BuildRequires:  golang(github.com/armon/go-metrics/datadog)
BuildRequires:  golang(github.com/armon/go-metrics/prometheus)
BuildRequires:  golang(github.com/armon/go-proxyproto)
BuildRequires:  golang(github.com/armon/go-radix)
BuildRequires:  golang(github.com/asaskevich/govalidator)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/arn)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/awserr)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/credentials/stscreds)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/defaults)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/ec2metadata)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/endpoints)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/request)
BuildRequires:  golang(github.com/aws/aws-sdk-go/aws/session)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/dynamodb)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/ec2)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/iam)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/iam/iamiface)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/kms)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/kms/kmsiface)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/s3)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/sts)
BuildRequires:  golang(github.com/aws/aws-sdk-go/service/sts/stsiface)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault)
BuildRequires:  golang(github.com/Azure/azure-sdk-for-go/storage)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/azure/auth)
BuildRequires:  golang(github.com/Azure/go-autorest/autorest/to)
BuildRequires:  golang(github.com/chrismalek/oktasdk-go/okta)
BuildRequires:  golang(github.com/cockroachdb/cockroach-go/crdb)
BuildRequires:  golang(github.com/coreos/go-semver/semver)
BuildRequires:  golang(github.com/denisenkom/go-mssqldb)
BuildRequires:  golang(github.com/duosecurity/duo_api_golang)
BuildRequires:  golang(github.com/duosecurity/duo_api_golang/authapi)
BuildRequires:  golang(github.com/elazarl/go-bindata-assetfs)
BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/fatih/structs)
BuildRequires:  golang(github.com/fullsailor/pkcs7)
BuildRequires:  golang(github.com/ghodss/yaml)
BuildRequires:  golang(github.com/go-errors/errors)
BuildRequires:  golang(github.com/go-ldap/ldap)
BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/gocql/gocql)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/golang/protobuf/ptypes)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/any)
BuildRequires:  golang(github.com/golang/protobuf/ptypes/timestamp)
BuildRequires:  golang(github.com/golang/snappy)
BuildRequires:  golang(github.com/google/go-github/github)
BuildRequires:  golang(github.com/hashicorp/consul/api)
BuildRequires:  golang(github.com/hashicorp/consul/lib)
BuildRequires:  golang(github.com/hashicorp/errwrap)
BuildRequires:  golang(github.com/hashicorp/go-cleanhttp)
BuildRequires:  golang(github.com/hashicorp/go-gcp-common/gcputil)
BuildRequires:  golang(github.com/hashicorp/go-hclog)
BuildRequires:  golang(github.com/hashicorp/go-immutable-radix)
BuildRequires:  golang(github.com/hashicorp/go-memdb)
BuildRequires:  golang(github.com/hashicorp/go-multierror)
BuildRequires:  golang(github.com/hashicorp/go-plugin)
BuildRequires:  golang(github.com/hashicorp/go-retryablehttp)
BuildRequires:  golang(github.com/hashicorp/go-rootcerts)
BuildRequires:  golang(github.com/hashicorp/go-sockaddr)
BuildRequires:  golang(github.com/hashicorp/go-syslog)
BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/hashicorp/go-version)
BuildRequires:  golang(github.com/hashicorp/golang-lru)
BuildRequires:  golang(github.com/hashicorp/hcl)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/ast)
BuildRequires:  golang(github.com/hashicorp/hcl/hcl/printer)
BuildRequires:  golang(github.com/hashicorp/nomad/api)
BuildRequires:  golang(github.com/influxdata/influxdb/client/v2)
BuildRequires:  golang(github.com/jefferai/isbadcipher)
BuildRequires:  golang(github.com/jefferai/jsonx)
BuildRequires:  golang(github.com/joyent/triton-go)
BuildRequires:  golang(github.com/joyent/triton-go/authentication)
BuildRequires:  golang(github.com/joyent/triton-go/errors)
BuildRequires:  golang(github.com/joyent/triton-go/storage)
BuildRequires:  golang(github.com/keybase/go-crypto/openpgp)
BuildRequires:  golang(github.com/keybase/go-crypto/openpgp/packet)
BuildRequires:  golang(github.com/kr/pretty)
BuildRequires:  golang(github.com/kr/text)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-colorable)
BuildRequires:  golang(github.com/michaelklishin/rabbit-hole)
BuildRequires:  golang(github.com/mitchellh/cli)
BuildRequires:  golang(github.com/mitchellh/copystructure)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/mitchellh/go-testing-interface)
BuildRequires:  golang(github.com/mitchellh/mapstructure)
BuildRequires:  golang(github.com/mitchellh/reflectwalk)
BuildRequires:  golang(github.com/ncw/swift)
BuildRequires:  golang(github.com/NYTimes/gziphandler)
BuildRequires:  golang(github.com/oklog/run)
BuildRequires:  golang(github.com/patrickmn/go-cache)
BuildRequires:  golang(github.com/pierrec/lz4)
BuildRequires:  golang(github.com/pkg/errors)
BuildRequires:  golang(github.com/posener/complete)
BuildRequires:  golang(github.com/pquerna/otp)
BuildRequires:  golang(github.com/pquerna/otp/totp)
BuildRequires:  golang(github.com/prometheus/client_golang/prometheus)
BuildRequires:  golang(github.com/prometheus/common/expfmt)
BuildRequires:  golang(github.com/ryanuber/columnize)
BuildRequires:  golang(github.com/ryanuber/go-glob)
BuildRequires:  golang(github.com/samuel/go-zookeeper/zk)
BuildRequires:  golang(github.com/SAP/go-hdb/driver)
BuildRequires:  golang(github.com/SermoDigital/jose/crypto)
BuildRequires:  golang(github.com/SermoDigital/jose/jws)
BuildRequires:  golang(github.com/SermoDigital/jose/jwt)
BuildRequires:  golang(go.etcd.io/etcd/client)
BuildRequires:  golang(go.etcd.io/etcd/clientv3)
BuildRequires:  golang(go.etcd.io/etcd/clientv3/concurrency)
BuildRequires:  golang(go.etcd.io/etcd/pkg/transport)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/crypto/blake2b)
BuildRequires:  golang(golang.org/x/crypto/chacha20poly1305)
BuildRequires:  golang(golang.org/x/crypto/cryptobyte)
BuildRequires:  golang(golang.org/x/crypto/cryptobyte/asn1)
BuildRequires:  golang(golang.org/x/crypto/curve25519)
BuildRequires:  golang(golang.org/x/crypto/ed25519)
BuildRequires:  golang(golang.org/x/crypto/hkdf)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/crypto/ssh/agent)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/net/idna)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(golang.org/x/time/rate)
BuildRequires:  golang(google.golang.org/api/googleapi)
BuildRequires:  golang(google.golang.org/api/iam/v1)
BuildRequires:  golang(google.golang.org/api/iterator)
BuildRequires:  golang(google.golang.org/api/option)
BuildRequires:  golang(google.golang.org/genproto/googleapis/cloud/kms/v1)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/grpclog)
BuildRequires:  golang(google.golang.org/grpc/keepalive)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(gopkg.in/mgo.v2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2)
BuildRequires:  golang(gopkg.in/square/go-jose.v2/jwt)
BuildRequires:  golang(layeh.com/radius)
BuildRequires:  golang(layeh.com/radius/rfc2865)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials)
BuildRequires:  golang(github.com/aliyun/alibaba-cloud-sdk-go/services/sts)
BuildRequires:  golang(github.com/go-test/deep)
BuildRequires:  golang(github.com/gogo/protobuf/proto)
BuildRequires:  golang(github.com/ory/dockertest)
BuildRequires:  golang(gopkg.in/ory-am/dockertest.v2)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
mv ui/app/adapters/license.js license-ui-app-adapters.js
mv ui/app/components/license-info.js license-info-ui-app-components.js
mv ui/app/controllers/vault/cluster/license.js license-ui-app-controllers-vault-cluster.js
mv ui/app/models/license.js license-ui-app-models.js
mv ui/app/routes/vault/cluster/license.js license-ui-app-routes-vault-cluster.js
mv ui/app/templates/components/license-info.hbs license-info-ui-app-templates-components.hbs
mv ui/app/templates/vault/cluster/license.hbs license-ui-app-templates-vault-cluster.hbs
mv website/LICENSE.md LICENSE-website.md
mv website/source/api/system/license.html.md license.html-website-source-api-system.md
mv builtin/credential/cert/test-fixtures/generate.txt generate-builtin-credential-cert-test-fixtures.txt
mv physical/foundationdb/README.md README-physical-foundationdb.md
mv plugins/database/mssql/README.md README-plugins-database-mssql.md
mv ui/README.md README-ui.md
mv ui/public/robots.txt robots-ui-public.txt
mv website/README.md README-website.md
mv website/source/404.html.md 404.html-website-source.md
mv website/source/robots.txt robots-website-source.txt
mv website/source/api/libraries.html.md libraries.html-website-source-api.md
mv website/source/api/overview.html.md overview.html-website-source-api.md
mv website/source/api/relatedtools.html.md relatedtools.html-website-source-api.md
mv website/source/api/auth/index.html.md index.html-website-source-api-auth.md
mv website/source/api/auth/app-id/index.html.md index.html-website-source-api-auth-app-id.md
mv website/source/api/auth/approle/index.html.md index.html-website-source-api-auth-approle.md
mv website/source/api/auth/aws/index.html.md index.html-website-source-api-auth-aws.md
mv website/source/api/auth/azure/index.html.md index.html-website-source-api-auth-azure.md
mv website/source/api/auth/cert/index.html.md index.html-website-source-api-auth-cert.md
mv website/source/api/auth/gcp/index.html.md index.html-website-source-api-auth-gcp.md
mv website/source/api/auth/github/index.html.md index.html-website-source-api-auth-github.md
mv website/source/api/auth/kubernetes/index.html.md index.html-website-source-api-auth-kubernetes.md
mv website/source/api/auth/ldap/index.html.md index.html-website-source-api-auth-ldap.md
mv website/source/api/auth/okta/index.html.md index.html-website-source-api-auth-okta.md
mv website/source/api/auth/radius/index.html.md index.html-website-source-api-auth-radius.md
mv website/source/api/auth/token/index.html.md index.html-website-source-api-auth-token.md
mv website/source/api/auth/userpass/index.html.md index.html-website-source-api-auth-userpass.md
mv website/source/api/auth/alicloud/index.html.md index.html-website-source-api-auth-alicloud.md
mv website/source/api/auth/jwt/index.html.md index.html-website-source-api-auth-jwt.md
mv website/source/api/auth/jwt/index_beta.html.md index_beta.html-website-source-api-auth-jwt.md
mv website/source/api/secret/index.html.md index.html-website-source-api-secret.md
mv website/source/api/secret/ad/index.html.md index.html-website-source-api-secret-ad.md
mv website/source/api/secret/aws/index.html.md index.html-website-source-api-secret-aws.md
mv website/source/api/secret/cassandra/index.html.md index.html-website-source-api-secret-cassandra.md
mv website/source/api/secret/consul/index.html.md index.html-website-source-api-secret-consul.md
mv website/source/api/secret/cubbyhole/index.html.md index.html-website-source-api-secret-cubbyhole.md
mv website/source/api/secret/databases/cassandra.html.md cassandra.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/hanadb.html.md hanadb.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/index.html.md index.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/influxdb.html.md influxdb.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/mongodb.html.md mongodb.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/mssql.html.md mssql.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/mysql-maria.html.md mysql-maria.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/oracle.html.md oracle.html-website-source-api-secret-databases.md
mv website/source/api/secret/databases/postgresql.html.md postgresql.html-website-source-api-secret-databases.md
mv website/source/api/secret/gcp/index.html.md index.html-website-source-api-secret-gcp.md
mv website/source/api/secret/identity/entity-alias.html.md entity-alias.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/entity.html.md entity.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/group-alias.html.md group-alias.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/group.html.md group.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/identity-groups.html.md identity-groups.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/index.html.md index.html-website-source-api-secret-identity.md
mv website/source/api/secret/identity/lookup.html.md lookup.html-website-source-api-secret-identity.md
mv website/source/api/secret/kv/index.html.md index.html-website-source-api-secret-kv.md
mv website/source/api/secret/kv/kv-v1.html.md kv-v1.html-website-source-api-secret-kv.md
mv website/source/api/secret/kv/kv-v2.html.md kv-v2.html-website-source-api-secret-kv.md
mv website/source/api/secret/mongodb/index.html.md index.html-website-source-api-secret-mongodb.md
mv website/source/api/secret/mssql/index.html.md index.html-website-source-api-secret-mssql.md
mv website/source/api/secret/mysql/index.html.md index.html-website-source-api-secret-mysql.md
mv website/source/api/secret/nomad/index.html.md index.html-website-source-api-secret-nomad.md
mv website/source/api/secret/pki/index.html.md index.html-website-source-api-secret-pki.md
mv website/source/api/secret/postgresql/index.html.md index.html-website-source-api-secret-postgresql.md
mv website/source/api/secret/rabbitmq/index.html.md index.html-website-source-api-secret-rabbitmq.md
mv website/source/api/secret/ssh/index.html.md index.html-website-source-api-secret-ssh.md
mv website/source/api/secret/totp/index.html.md index.html-website-source-api-secret-totp.md
mv website/source/api/secret/transit/index.html.md index.html-website-source-api-secret-transit.md
mv website/source/api/secret/alicloud/index.html.md index.html-website-source-api-secret-alicloud.md
mv website/source/api/secret/azure/index.html.md index.html-website-source-api-secret-azure.md
mv website/source/api/secret/gcpkms/index.html.md index.html-website-source-api-secret-gcpkms.md
mv website/source/api/system/init.html.md init.html-website-source-api-system.md
mv website/source/api/system/internal-specs-openapi.html.md internal-specs-openapi.html-website-source-api-system.md
mv website/source/api/system/key-status.html.md key-status.html-website-source-api-system.md
mv website/source/api/system/leader.html.md leader.html-website-source-api-system.md
mv website/source/api/system/leases.html.md leases.html-website-source-api-system.md
mv website/source/api/system/mounts.html.md mounts.html-website-source-api-system.md
mv website/source/api/system/namespaces.html.md namespaces.html-website-source-api-system.md
mv website/source/api/system/plugins-catalog.html.md plugins-catalog.html-website-source-api-system.md
mv website/source/api/system/plugins-reload-backend.html.md plugins-reload-backend.html-website-source-api-system.md
mv website/source/api/system/policies.html.md policies.html-website-source-api-system.md
mv website/source/api/system/policy.html.md policy.html-website-source-api-system.md
mv website/source/api/system/raw.html.md raw.html-website-source-api-system.md
mv website/source/api/system/rekey-recovery-key.html.md rekey-recovery-key.html-website-source-api-system.md
mv website/source/api/system/rekey.html.md rekey.html-website-source-api-system.md
mv website/source/api/system/remount.html.md remount.html-website-source-api-system.md
mv website/source/api/system/rotate.html.md rotate.html-website-source-api-system.md
mv website/source/api/system/seal-status.html.md seal-status.html-website-source-api-system.md
mv website/source/api/system/seal.html.md seal.html-website-source-api-system.md
mv website/source/api/system/step-down.html.md step-down.html-website-source-api-system.md
mv website/source/api/system/tools.html.md tools.html-website-source-api-system.md
mv website/source/api/system/unseal.html.md unseal.html-website-source-api-system.md
mv website/source/api/system/wrapping-lookup.html.md wrapping-lookup.html-website-source-api-system.md
mv website/source/api/system/wrapping-rewrap.html.md wrapping-rewrap.html-website-source-api-system.md
mv website/source/api/system/wrapping-unwrap.html.md wrapping-unwrap.html-website-source-api-system.md
mv website/source/api/system/wrapping-wrap.html.md wrapping-wrap.html-website-source-api-system.md
mv website/source/api/system/audit-hash.html.md audit-hash.html-website-source-api-system.md
mv website/source/api/system/audit.html.md audit.html-website-source-api-system.md
mv website/source/api/system/auth.html.md auth.html-website-source-api-system.md
mv website/source/api/system/capabilities-accessor.html.md capabilities-accessor.html-website-source-api-system.md
mv website/source/api/system/capabilities-self.html.md capabilities-self.html-website-source-api-system.md
mv website/source/api/system/capabilities.html.md capabilities.html-website-source-api-system.md
mv website/source/api/system/config-auditing.html.md config-auditing.html-website-source-api-system.md
mv website/source/api/system/config-control-group.html.md config-control-group.html-website-source-api-system.md
mv website/source/api/system/config-cors.html.md config-cors.html-website-source-api-system.md
mv website/source/api/system/config-ui.html.md config-ui.html-website-source-api-system.md
mv website/source/api/system/control-group.html.md control-group.html-website-source-api-system.md
mv website/source/api/system/generate-root.html.md generate-root.html-website-source-api-system.md
mv website/source/api/system/health.html.md health.html-website-source-api-system.md
mv website/source/api/system/index.html.md index.html-website-source-api-system.md
mv website/source/api/system/internal-ui-mounts.html.md internal-ui-mounts.html-website-source-api-system.md
mv website/source/api/system/mfa/duo.html.md duo.html-website-source-api-system-mfa.md
mv website/source/api/system/mfa/index.html.md index.html-website-source-api-system-mfa.md
mv website/source/api/system/mfa/okta.html.md okta.html-website-source-api-system-mfa.md
mv website/source/api/system/mfa/pingid.html.md pingid.html-website-source-api-system-mfa.md
mv website/source/api/system/mfa/totp.html.md totp.html-website-source-api-system-mfa.md
mv website/source/api/system/replication/index.html.md index.html-website-source-api-system-replication.md
mv website/source/api/system/replication/replication-dr.html.md replication-dr.html-website-source-api-system-replication.md
mv website/source/api/system/replication/replication-performance.html.md replication-performance.html-website-source-api-system-replication.md
mv website/source/guides/index.html.md index.html-website-source-guides.md
mv website/source/guides/encryption/index.html.md index.html-website-source-guides-encryption.md
mv website/source/guides/encryption/spring-demo.html.md spring-demo.html-website-source-guides-encryption.md
mv website/source/guides/encryption/transit-rewrap.html.md transit-rewrap.html-website-source-guides-encryption.md
mv website/source/guides/encryption/transit.html.md transit.html-website-source-guides-encryption.md
mv website/source/guides/getting-started/index.html.md index.html-website-source-guides-getting-started.md
mv website/source/guides/identity/approle-trusted-entities.html.md approle-trusted-entities.html-website-source-guides-identity.md
mv website/source/guides/identity/authentication.html.md authentication.html-website-source-guides-identity.md
mv website/source/guides/identity/control-groups.html.md control-groups.html-website-source-guides-identity.md
mv website/source/guides/identity/identity.html.md identity.html-website-source-guides-identity.md
mv website/source/guides/identity/index.html.md index.html-website-source-guides-identity.md
mv website/source/guides/identity/lease.html.md lease.html-website-source-guides-identity.md
mv website/source/guides/identity/policies.html.md policies.html-website-source-guides-identity.md
mv website/source/guides/identity/policy-templating.html.md policy-templating.html-website-source-guides-identity.md
mv website/source/guides/identity/secure-intro.html.md secure-intro.html-website-source-guides-identity.md
mv website/source/guides/identity/sentinel.html.md sentinel.html-website-source-guides-identity.md
mv website/source/guides/operations/autounseal-aws-kms.html.md autounseal-aws-kms.html-website-source-guides-operations.md
mv website/source/guides/operations/deployment-guide.html.md deployment-guide.html-website-source-guides-operations.md
mv website/source/guides/operations/disaster-recovery.html.md disaster-recovery.html-website-source-guides-operations.md
mv website/source/guides/operations/generate-root.html.md generate-root.html-website-source-guides-operations.md
mv website/source/guides/operations/index.html.md index.html-website-source-guides-operations.md
mv website/source/guides/operations/monitoring.html.md monitoring.html-website-source-guides-operations.md
mv website/source/guides/operations/mount-filter.html.md mount-filter.html-website-source-guides-operations.md
mv website/source/guides/operations/multi-tenant.html.md multi-tenant.html-website-source-guides-operations.md
mv website/source/guides/operations/performance-nodes.html.md performance-nodes.html-website-source-guides-operations.md
mv website/source/guides/operations/plugin-backends.html.md plugin-backends.html-website-source-guides-operations.md
mv website/source/guides/operations/production.html.md production.html-website-source-guides-operations.md
mv website/source/guides/operations/reference-architecture.html.md reference-architecture.html-website-source-guides-operations.md
mv website/source/guides/operations/rekeying-and-rotating.html.md rekeying-and-rotating.html-website-source-guides-operations.md
mv website/source/guides/operations/replication.html.md replication.html-website-source-guides-operations.md
mv website/source/guides/operations/seal-wrap.html.md seal-wrap.html-website-source-guides-operations.md
mv website/source/guides/operations/vault-ha-consul.html.md vault-ha-consul.html-website-source-guides-operations.md
mv website/source/guides/secret-mgmt/app-integration.html.md app-integration.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/cubbyhole.html.md cubbyhole.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/db-root-rotation.html.md db-root-rotation.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/dynamic-secrets.html.md dynamic-secrets.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/index.html.md index.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/pki-engine.html.md pki-engine.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/ssh-otp.html.md ssh-otp.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/static-secrets.html.md static-secrets.html-website-source-guides-secret-mgmt.md
mv website/source/guides/secret-mgmt/versioned-kv.html.md versioned-kv.html-website-source-guides-secret-mgmt.md
mv website/source/intro/getting-started/apis.html.md apis.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/authentication.html.md authentication.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/deploy.html.md deploy.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/dev-server.html.md dev-server.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/dynamic-secrets.html.md dynamic-secrets.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/first-secret.html.md first-secret.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/help.html.md help.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/index.html.md index.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/next-steps.html.md next-steps.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/policies.html.md policies.html-website-source-intro-getting-started.md
mv website/source/intro/getting-started/secrets-engines.html.md secrets-engines.html-website-source-intro-getting-started.md
mv terraform/aws/README.md README-terraform-aws.md

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE license-ui-app-adapters.js license-info-ui-app-components.js
%license license-ui-app-controllers-vault-cluster.js license-ui-app-models.js
%license license-ui-app-routes-vault-cluster.js
%license license-info-ui-app-templates-components.hbs
%license license-ui-app-templates-vault-cluster.hbs LICENSE-website.md
%license license.html-website-source-api-system.md
%doc CONTRIBUTING.md CHANGELOG.md README.md
%doc generate-builtin-credential-cert-test-fixtures.txt
%doc README-physical-foundationdb.md README-plugins-database-mssql.md
%doc README-ui.md robots-ui-public.txt README-website.md docs
%doc 404.html-website-source.md robots-website-source.txt
%doc libraries.html-website-source-api.md overview.html-website-source-api.md
%doc relatedtools.html-website-source-api.md
%doc index.html-website-source-api-auth.md
%doc index.html-website-source-api-auth-app-id.md
%doc index.html-website-source-api-auth-approle.md
%doc index.html-website-source-api-auth-aws.md
%doc index.html-website-source-api-auth-azure.md
%doc index.html-website-source-api-auth-cert.md
%doc index.html-website-source-api-auth-gcp.md
%doc index.html-website-source-api-auth-github.md
%doc index.html-website-source-api-auth-kubernetes.md
%doc index.html-website-source-api-auth-ldap.md
%doc index.html-website-source-api-auth-okta.md
%doc index.html-website-source-api-auth-radius.md
%doc index.html-website-source-api-auth-token.md
%doc index.html-website-source-api-auth-userpass.md
%doc index.html-website-source-api-auth-alicloud.md
%doc index.html-website-source-api-auth-jwt.md
%doc index_beta.html-website-source-api-auth-jwt.md
%doc index.html-website-source-api-secret.md
%doc index.html-website-source-api-secret-ad.md
%doc index.html-website-source-api-secret-aws.md
%doc index.html-website-source-api-secret-cassandra.md
%doc index.html-website-source-api-secret-consul.md
%doc index.html-website-source-api-secret-cubbyhole.md
%doc cassandra.html-website-source-api-secret-databases.md
%doc hanadb.html-website-source-api-secret-databases.md
%doc index.html-website-source-api-secret-databases.md
%doc influxdb.html-website-source-api-secret-databases.md
%doc mongodb.html-website-source-api-secret-databases.md
%doc mssql.html-website-source-api-secret-databases.md
%doc mysql-maria.html-website-source-api-secret-databases.md
%doc oracle.html-website-source-api-secret-databases.md
%doc postgresql.html-website-source-api-secret-databases.md
%doc index.html-website-source-api-secret-gcp.md
%doc entity-alias.html-website-source-api-secret-identity.md
%doc entity.html-website-source-api-secret-identity.md
%doc group-alias.html-website-source-api-secret-identity.md
%doc group.html-website-source-api-secret-identity.md
%doc identity-groups.html-website-source-api-secret-identity.md
%doc index.html-website-source-api-secret-identity.md
%doc lookup.html-website-source-api-secret-identity.md
%doc index.html-website-source-api-secret-kv.md
%doc kv-v1.html-website-source-api-secret-kv.md
%doc kv-v2.html-website-source-api-secret-kv.md
%doc index.html-website-source-api-secret-mongodb.md
%doc index.html-website-source-api-secret-mssql.md
%doc index.html-website-source-api-secret-mysql.md
%doc index.html-website-source-api-secret-nomad.md
%doc index.html-website-source-api-secret-pki.md
%doc index.html-website-source-api-secret-postgresql.md
%doc index.html-website-source-api-secret-rabbitmq.md
%doc index.html-website-source-api-secret-ssh.md
%doc index.html-website-source-api-secret-totp.md
%doc index.html-website-source-api-secret-transit.md
%doc index.html-website-source-api-secret-alicloud.md
%doc index.html-website-source-api-secret-azure.md
%doc index.html-website-source-api-secret-gcpkms.md
%doc init.html-website-source-api-system.md
%doc internal-specs-openapi.html-website-source-api-system.md
%doc key-status.html-website-source-api-system.md
%doc leader.html-website-source-api-system.md
%doc leases.html-website-source-api-system.md
%doc mounts.html-website-source-api-system.md
%doc namespaces.html-website-source-api-system.md
%doc plugins-catalog.html-website-source-api-system.md
%doc plugins-reload-backend.html-website-source-api-system.md
%doc policies.html-website-source-api-system.md
%doc policy.html-website-source-api-system.md
%doc raw.html-website-source-api-system.md
%doc rekey-recovery-key.html-website-source-api-system.md
%doc rekey.html-website-source-api-system.md
%doc remount.html-website-source-api-system.md
%doc rotate.html-website-source-api-system.md
%doc seal-status.html-website-source-api-system.md
%doc seal.html-website-source-api-system.md
%doc step-down.html-website-source-api-system.md
%doc tools.html-website-source-api-system.md
%doc unseal.html-website-source-api-system.md
%doc wrapping-lookup.html-website-source-api-system.md
%doc wrapping-rewrap.html-website-source-api-system.md
%doc wrapping-unwrap.html-website-source-api-system.md
%doc wrapping-wrap.html-website-source-api-system.md
%doc audit-hash.html-website-source-api-system.md
%doc audit.html-website-source-api-system.md
%doc auth.html-website-source-api-system.md
%doc capabilities-accessor.html-website-source-api-system.md
%doc capabilities-self.html-website-source-api-system.md
%doc capabilities.html-website-source-api-system.md
%doc config-auditing.html-website-source-api-system.md
%doc config-control-group.html-website-source-api-system.md
%doc config-cors.html-website-source-api-system.md
%doc config-ui.html-website-source-api-system.md
%doc control-group.html-website-source-api-system.md
%doc generate-root.html-website-source-api-system.md
%doc health.html-website-source-api-system.md
%doc index.html-website-source-api-system.md
%doc internal-ui-mounts.html-website-source-api-system.md
%doc duo.html-website-source-api-system-mfa.md
%doc index.html-website-source-api-system-mfa.md
%doc okta.html-website-source-api-system-mfa.md
%doc pingid.html-website-source-api-system-mfa.md
%doc totp.html-website-source-api-system-mfa.md
%doc index.html-website-source-api-system-replication.md
%doc replication-dr.html-website-source-api-system-replication.md
%doc replication-performance.html-website-source-api-system-replication.md
%doc index.html-website-source-guides.md
%doc index.html-website-source-guides-encryption.md
%doc spring-demo.html-website-source-guides-encryption.md
%doc transit-rewrap.html-website-source-guides-encryption.md
%doc transit.html-website-source-guides-encryption.md
%doc index.html-website-source-guides-getting-started.md
%doc approle-trusted-entities.html-website-source-guides-identity.md
%doc authentication.html-website-source-guides-identity.md
%doc control-groups.html-website-source-guides-identity.md
%doc identity.html-website-source-guides-identity.md
%doc index.html-website-source-guides-identity.md
%doc lease.html-website-source-guides-identity.md
%doc policies.html-website-source-guides-identity.md
%doc policy-templating.html-website-source-guides-identity.md
%doc secure-intro.html-website-source-guides-identity.md
%doc sentinel.html-website-source-guides-identity.md
%doc autounseal-aws-kms.html-website-source-guides-operations.md
%doc deployment-guide.html-website-source-guides-operations.md
%doc disaster-recovery.html-website-source-guides-operations.md
%doc generate-root.html-website-source-guides-operations.md
%doc index.html-website-source-guides-operations.md
%doc monitoring.html-website-source-guides-operations.md
%doc mount-filter.html-website-source-guides-operations.md
%doc multi-tenant.html-website-source-guides-operations.md
%doc performance-nodes.html-website-source-guides-operations.md
%doc plugin-backends.html-website-source-guides-operations.md
%doc production.html-website-source-guides-operations.md
%doc reference-architecture.html-website-source-guides-operations.md
%doc rekeying-and-rotating.html-website-source-guides-operations.md
%doc replication.html-website-source-guides-operations.md
%doc seal-wrap.html-website-source-guides-operations.md
%doc vault-ha-consul.html-website-source-guides-operations.md
%doc app-integration.html-website-source-guides-secret-mgmt.md
%doc cubbyhole.html-website-source-guides-secret-mgmt.md
%doc db-root-rotation.html-website-source-guides-secret-mgmt.md
%doc dynamic-secrets.html-website-source-guides-secret-mgmt.md
%doc index.html-website-source-guides-secret-mgmt.md
%doc pki-engine.html-website-source-guides-secret-mgmt.md
%doc ssh-otp.html-website-source-guides-secret-mgmt.md
%doc static-secrets.html-website-source-guides-secret-mgmt.md
%doc versioned-kv.html-website-source-guides-secret-mgmt.md
%doc apis.html-website-source-intro-getting-started.md
%doc authentication.html-website-source-intro-getting-started.md
%doc deploy.html-website-source-intro-getting-started.md
%doc dev-server.html-website-source-intro-getting-started.md
%doc dynamic-secrets.html-website-source-intro-getting-started.md
%doc first-secret.html-website-source-intro-getting-started.md
%doc help.html-website-source-intro-getting-started.md
%doc index.html-website-source-intro-getting-started.md
%doc next-steps.html-website-source-intro-getting-started.md
%doc policies.html-website-source-intro-getting-started.md
%doc secrets-engines.html-website-source-intro-getting-started.md
%doc README-terraform-aws.md

%gopkgfiles

%changelog

